using System.Globalization;
using Crystalfly.Core.Configuration;

namespace Crystalfly.App.ViewModels;

public sealed class LocalizationViewModel : ViewModelBase
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["NavLaunch"] = "Launch",
        ["NavVersions"] = "Instances",
        ["NavManage"] = "Manage",
        ["NavSpeedrun"] = "Speedrun",
        ["NavDownloads"] = "Downloads",
        ["NavSettings"] = "Settings",
        ["WindowMinimize"] = "Minimize",
        ["WindowMaximize"] = "Maximize / restore",
        ["WindowClose"] = "Close",
        ["Ready"] = "Ready",
        ["ReadyHint"] = "The selected instance passed launch checks.",
        ["NoInstance"] = "No instance selected",
        ["ChooseRoot"] = "Choose a version root to discover Hollow Knight instances.",
        ["LaunchGame"] = "Launch game",
        ["LaunchIssues"] = "Launch issues",
        ["LaunchIssueCountFormat"] = "{0} launch issues",
        ["LaunchWarningTitle"] = "Review launch issues",
        ["LaunchWarningMessage"] = "Mod integrity or dependency issues were found. Review them before continuing.",
        ["LaunchBlockedTitle"] = "Launch blocked",
        ["ForceLaunch"] = "Force launch",
        ["DoNotRemindLaunchWarnings"] = "Do not remind me again while these exact issues stay unchanged",
        ["LaunchIssueExecutableMissing"] = "The game executable is missing",
        ["LaunchIssueGameAlreadyRunning"] = "Hollow Knight is already running",
        ["LaunchIssueUnknownBuild"] = "The build and Loader combination is unsupported",
        ["LaunchIssueLoaderConflict"] = "Conflicting Loader files were detected",
        ["LaunchIssueLoaderDrifted"] = "Loader files have drifted",
        ["LaunchIssueMissingDependency"] = "A required Mod dependency is missing",
        ["LaunchIssueDisabledDependency"] = "A required Mod dependency is disabled",
        ["LaunchIssueTransactionNeedsAttention"] = "A file transaction needs attention",
        ["LaunchIssueLocalLowNotReady"] = "The isolated save directory is not ready",
        ["LaunchIssueModCriticalFileMissing"] = "A required Mod file is missing",
        ["LaunchIssueModModifiedFile"] = "A Mod file was modified",
        ["LaunchIssueModExtraFile"] = "A Mod contains an extra file",
        ["LaunchIssueExternalMod"] = "An unmanaged external Mod was found",
        ["LaunchIssueModIndeterminate"] = "Mod integrity could not be determined",
        ["Refresh"] = "Refresh",
        ["ManageInstance"] = "Instance settings",
        ["LoaderFiles"] = "Game and Loader files",
        ["ModDependencies"] = "Mod dependencies",
        ["SaveIsolation"] = "Save isolation",
        ["Complete"] = "Complete",
        ["NoConflicts"] = "No conflicts",
        ["Mounted"] = "Ready",
        ["Instances"] = "Instances",
        ["InstancesHint"] = "Known versions and full-copy environments under the selected root.",
        ["SearchInstances"] = "Search instances",
        ["Overview"] = "Overview",
        ["Loader"] = "Loader",
        ["Mods"] = "Mods",
        ["Snapshots"] = "Save Snapshots",
        ["Logs"] = "Logs",
        ["Config"] = "Config",
        ["ConfigHint"] = "Edit the instance game settings file (AppConfig.ini). Video, audio, language and key bindings are stored elsewhere and are not editable here.",
        ["Accessibility"] = "Accessibility",
        ["ReducedCameraShake"] = "Reduced camera shake",
        ["ReducedControllerRumble"] = "Reduced controller rumble",
        ["AdvancedConfig"] = "Advanced key/value",
        ["AdvancedConfigHint"] = "Edit any section, key or value directly. Unknown fields are preserved.",
        ["AddEntry"] = "Add entry",
        ["RemoveEntry"] = "Remove",
        ["SaveConfig"] = "Save",
        ["ResetConfig"] = "Reset",
        ["ConfigSaved"] = "Configuration saved",
        ["ConfigSection"] = "Section",
        ["ConfigKey"] = "Key",
        ["ConfigValue"] = "Value",
        ["ConfigLocked"] = "Close the game to edit its configuration.",
        ["CurrentSave"] = "Current instance saves",
        ["EditSave"] = "Edit save",
        ["SaveSlot"] = "Save slot",
        ["NoSaveSlots"] = "This instance does not have any save files yet.",
        ["SpeedrunTitle"] = "Official speedrun environments",
        ["SpeedrunHint"] = "Create a dedicated verified copy. Daily instances are never modified.",
        ["SpeedrunComingSoon"] = "Coming soon",
        ["SpeedrunComingSoonHint"] = "The official speedrun workflow is being rebuilt for direct plugin installation.",
        ["SpeedrunCreate"] = "Create environment",
        ["SpeedrunInstances"] = "Speedrun environments",
        ["SpeedrunInstancesHint"] = "Dedicated full copies with fixed RuntimePatches assets.",
        ["SpeedrunNoInstance"] = "Select an environment or create a new one.",
        ["SpeedrunTemplateExpired"] = "Template expired. Recreate this environment before an official run.",
        ["SpeedrunTechnicalReady"] = "RuntimePatches environment",
        ["SpeedrunNeedsRebuild"] = "This environment is not a current RuntimePatches template.",
        ["SpeedrunConfiguration"] = "RuntimePatches configuration",
        ["SpeedrunConfigurationInvalid"] = "RuntimePatches configuration is invalid",
        ["SpeedrunFeatureWarnings"] = "FasterIntroSkip must be off when the opening cinematic is timed. MiniSaveStates is only for explicitly permitted individual-level categories and must not be loaded during a run. Confirm all category rules before starting.",
        ["SpeedrunFeatureUnavailable"] = "Unavailable for this game version",
        ["SpeedrunEnvironmentName"] = "Environment name",
        ["SpeedrunSelectVanillaSource"] = "Select a clean Vanilla source instance",
        ["SpeedrunVerifyAndLaunch"] = "Verify and launch",
        ["SpeedrunReinstall"] = "Reinstall RuntimePatches",
        ["SpeedrunEnvironmentTab"] = "Environment",
        ["SpeedrunActivityTab"] = "Activity",
        ["SpeedrunGameHollowKnight"] = "Hollow Knight",
        ["SpeedrunGameSilksong"] = "Hollow Knight: Silksong",
        ["SpeedrunActivityTitle"] = "Podium activity",
        ["SpeedrunActivityHint"] = "New verified world records and podium results from official Speedrun.com boards.",
        ["SpeedrunGame"] = "Game",
        ["SpeedrunCategory"] = "Category",
        ["SpeedrunRefresh"] = "Check for new results",
        ["SpeedrunActivityAll"] = "All",
        ["SpeedrunActivityLoading"] = "Checking official boards...",
        ["SpeedrunActivityUnavailable"] = "Activity is unavailable right now.",
        ["SpeedrunActivityReady"] = "Monitoring active",
        ["SpeedrunActivityCached"] = "Cached board data",
        ["SpeedrunActivityUpdatedAt"] = "Checked {0}",
        ["SpeedrunActivityPartialFailure"] = "{0} boards could not be checked; their previous baselines were preserved.",
        ["SpeedrunActivityEmpty"] = "Monitoring is established. Future podium changes will appear here.",
        ["SpeedrunActivityWorldRecord"] = "World record",
        ["SpeedrunActivityTiedWorldRecord"] = "Tied world record",
        ["SpeedrunActivitySecond"] = "Second place",
        ["SpeedrunActivityThird"] = "Third place",
        ["SpeedrunActivityToastWorldRecord"] = "{0} set a world record in {1}: {2}",
        ["SpeedrunActivityToastTiedWorldRecord"] = "{0} tied the world record in {1}: {2}",
        ["SpeedrunActivityToastSecond"] = "{0} reached second place in {1}: {2}",
        ["SpeedrunActivityToastThird"] = "{0} reached third place in {1}: {2}",
        ["SpeedrunRank"] = "Rank",
        ["SpeedrunRunner"] = "Runner",
        ["SpeedrunTime"] = "Time",
        ["SpeedrunDate"] = "Date",
        ["SpeedrunOpenRun"] = "Open result",
        ["AboutSpeedrunComData"] = "Speedrun.com activity",
        ["AboutSpeedrunComDataDescription"] = "Official categories and verified podium results are checked on demand. Baselines and the latest 100 events are stored locally.",
        ["CreateEnvironment"] = "Create environment",
        ["DownloadsTitle"] = "Downloads",
        ["DownloadsHint"] = "Steam public builds and cached packages.",
        ["SteamAccount"] = "Steam account",
        ["SignInQr"] = "Sign in with QR",
        ["SignOut"] = "Sign out",
        ["SteamProxyDetected"] = "System proxy detected",
        ["SteamProxyDirect"] = "Direct network",
        ["SteamConnecting"] = "Connecting to Steam...",
        ["SteamScanQr"] = "Scan with the Steam mobile app",
        ["SteamNetworkReconnecting"] = "Reconnecting to Steam...",
        ["SteamNetworkTimeout"] = "Steam network request timed out",
        ["SteamNetworkHttpError"] = "Steam server returned HTTP error",
        ["SteamNetworkDisconnected"] = "Steam connection was interrupted",
        ["SteamNetworkUnavailable"] = "Steam network is unavailable",
        ["RefreshSteamNetwork"] = "Recheck Steam network",
        ["SignInWithPassword"] = "Sign in with password",
        ["SwitchToPasswordLogin"] = "Sign in with password",
        ["SwitchToQrLogin"] = "Use QR code instead",
        ["SteamUsername"] = "Username",
        ["SteamPassword"] = "Password",
        ["SteamLogin"] = "Sign in",
        ["SteamCredentialsRequired"] = "Enter a Steam username and password.",
        ["SteamGuardEmailTitle"] = "Email verification code",
        ["SteamGuardEmailMessage"] = "Enter the code sent to",
        ["SteamGuardDeviceTitle"] = "Mobile app code",
        ["SteamGuardDeviceMessage"] = "Enter the code shown in the Steam mobile app.",
        ["SteamGuardCodePlaceholder"] = "Steam Guard code",
        ["SteamGuardIncorrect"] = "That code was incorrect. Try again.",
        ["SteamDeviceConfirmationTitle"] = "Confirm sign-in",
        ["SteamDeviceConfirmationMessage"] = "Open the Steam mobile app and approve this sign-in. You can also switch to entering a code instead.",
        ["SteamDeviceConfirmationAccept"] = "I approved it",
        ["SteamDeviceConfirmationSwitchToCode"] = "Enter a code instead",
        ["AdoptExternalContent"] = "Adopt external Mods & Loader",
        ["AdoptExternalContentTitle"] = "Adopt external content",
        ["AdoptExternalContentMessage"] = "This instance has {0} external Mod(s) that are not managed by Crystalfly. Adopt them into the mod list? Game files stay unchanged.",
        ["AdoptExternalContentMessageNoMods"] = "This instance has an external Loader that is not managed by Crystalfly. Adopt it into the Loader state? Game files stay unchanged.",
        ["AdoptExternalContentDone"] = "Adopted external Mods and Loader.",
        ["AdoptExternalContentFailed"] = "Some external content could not be adopted:",
        ["MatchToCatalog"] = "Match to catalog",
        ["MatchToCatalogTitle"] = "Match mod to catalog",
        ["MatchToCatalogMessage"] = "Multiple catalog mods could match \"{0}\". Pick the one that corresponds to the installed files.",
        ["MatchToCatalogDone"] = "Matched the mod to its catalog entry.",
        ["MatchToCatalogFailed"] = "Could not match the mod to the catalog:",
        ["MatchToCatalogNoMatch"] = "No catalog mod matched the installed files.",
        ["SettingsTitle"] = "Settings",
        ["SettingsGeneral"] = "General",
        ["SettingsNetwork"] = "Network",
        ["SettingsCatalog"] = "Catalog",
        ["SettingsUpdates"] = "Updates",
        ["SettingsAbout"] = "About",
        ["AboutTitle"] = "About Crystalfly",
        ["AboutDescription"] = "A Hollow Knight version and Mod manager for Windows.",
        ["OnboardingReopen"] = "View the getting-started guide",
        ["OnboardingSection"] = "Getting started",
        ["OnboardingSectionHint"] = "Reopen the first-run wizard that explains how to import a game, install a Loader and add Mods.",
        ["OnboardingStepPosition"] = "Step {0} of {1}",
        ["OnboardingNext"] = "Next",
        ["OnboardingBack"] = "Back",
        ["OnboardingSkip"] = "Skip",
        ["OnboardingFinish"] = "Get started",
        ["OnboardingStepWelcomeTitle"] = "Welcome to Crystalfly",
        ["OnboardingStepWelcomeDescription"] = "Crystalfly manages Hollow Knight versions, Loaders and Mods. This short guide walks through the essentials.",
        ["OnboardingStepImportTitle"] = "Find your game",
        ["OnboardingStepImportDescription"] = "Crystalfly needs to know where Hollow Knight is installed. Open Settings > Game directories and scan your Steam library, or scan all drives and pick the folder that contains hollow_knight.exe.",
        ["OnboardingStepSelectInstanceTitle"] = "Choose an instance",
        ["OnboardingStepSelectInstanceDescription"] = "Each detected game folder becomes an instance on the Versions page. Select one to manage it. The last selected instance is remembered next launch.",
        ["OnboardingStepLoaderTitle"] = "Install a Loader",
        ["OnboardingStepLoaderDescription"] = "Most Mods need a Loader. On the instance's Loader tab, pick Modding API or BepInEx and install it. Imported existing installs can be adopted or matched to the catalog in one step.",
        ["OnboardingStepModsTitle"] = "Add Mods",
        ["OnboardingStepModsDescription"] = "Download Mods from the Downloads > Mod market for the selected instance, or import your own. Unmanaged external Mods can be adopted and matched to their catalog entries so dependencies resolve.",
        ["OnboardingStepLaunchTitle"] = "Launch the game",
        ["OnboardingStepLaunchDescription"] = "Back on the Launch page, Crystalfly checks game files, Loader and Mod health before starting Hollow Knight. Resolve any warnings shown on the launch panel.",
        ["OnboardingStepExtraTitle"] = "More to explore",
        ["OnboardingStepExtraDescription"] = "The Settings page covers network, catalog and appearance. The Speedrun page provides official speedrun templates and live activity. Come back any time via Settings > About.",
        ["OnboardingStepFinishTitle"] = "You are all set",
        ["OnboardingStepFinishDescription"] = "That is it. If anything goes wrong, error panels explain what to fix. You can reopen this guide anytime from Settings > About.",
        ["AboutContributors"] = "Contributors",
        ["AboutContributorValue"] = "JWST (wzxnb2333)",
        ["ProjectRepository"] = "Project repository",
        ["OpenRepository"] = "Open in browser",
        ["OpenSourceLicense"] = "Open-source license",
        ["LicenseName"] = "GPL-3.0-only",
        ["AboutDesignReferences"] = "Design and workflow references",
        ["AboutDesignReferencesDescription"] = "PCL2, Lumafly, and Scarab informed Crystalfly's information architecture and management workflows; their code is not included.",
        ["AboutOpenSourceComponents"] = "Open-source components",
        ["AboutOpenSourceComponentsDescription"] = "Crystalfly uses these components for UI, Steam communication, icons, and Markdown rendering. See each repository for its license.",
        ["AboutModCatalogAndTranslations"] = "Mod catalog and Chinese translations",
        ["AboutModCatalogAndTranslationsDescription"] = "Official Mod metadata comes from HK ModLinks. Crystalfly independently maintains the Chinese Mod names, descriptions, and tags.",
        ["VersionRoot"] = "Version root",
        ["Browse"] = "Browse",
        ["Language"] = "Language",
        ["Theme"] = "Theme",
        ["Motion"] = "Motion",
        ["MotionFollowSystem"] = "Follow system",
        ["MotionReduced"] = "Reduced motion",
        ["MotionOff"] = "Off",
        ["AccentColor"] = "Theme color",
        ["AccentColorHint"] = "Choose an accent color. The final circle opens a custom color picker.",
        ["AccentBlue"] = "Blue",
        ["AccentIndigo"] = "Indigo",
        ["AccentCrystalPurple"] = "Crystal purple",
        ["AccentRose"] = "Rose",
        ["AccentOrange"] = "Orange",
        ["AccentGreen"] = "Green",
        ["AccentCyan"] = "Cyan",
        ["AccentCustom"] = "Custom color",
        ["AccentColorPickerTitle"] = "Custom theme color",
        ["AccentOriginal"] = "Original",
        ["AccentNew"] = "New",
        ["AccentHex"] = "HEX",
        ["AccentInvalid"] = "Enter a six-digit HEX color.",
        ["BackgroundImage"] = "Background image",
        ["BackgroundImageHint"] = "Use a global background or override it for the current instance.",
        ["BackgroundScopeGlobal"] = "Global",
        ["BackgroundScopeGlobalHint"] = "Edit the background inherited by all instances.",
        ["BackgroundScopeInstance"] = "Current instance",
        ["BackgroundScopeInstanceHint"] = "Edit an independent background for the selected instance.",
        ["BackgroundSelect"] = "Choose image",
        ["BackgroundSelectHint"] = "Choose a PNG, JPEG, WebP, or BMP image up to 25 MiB.",
        ["BackgroundDelete"] = "Delete background",
        ["BackgroundRestoreGlobal"] = "Restore global",
        ["BackgroundOpacity"] = "Background opacity",
        ["BackgroundOpacityHint"] = "Adjust only the background image opacity.",
        ["BackgroundPreviewEmpty"] = "No background image",
        ["BackgroundNoInstance"] = "No current instance",
        ["BackgroundNotConfigured"] = "No global background is configured.",
        ["BackgroundGlobalConfigured"] = "Used by instances without an independent background.",
        ["BackgroundInstanceInherited"] = "Inheriting the global background.",
        ["BackgroundInstanceIndependent"] = "Using an independent instance background.",
        ["GitHubRoute"] = "Download route",
        ["GitHubRouteHint"] = "Choose a route or let smart selection probe and fail over between available routes.",
        ["OfflineMode"] = "Offline mode",
        ["OfflineModeHint"] = "Use only local data and verified caches. Network downloads wait until offline mode is disabled.",
        ["GitHubDirect"] = "GitHub direct",
        ["GitHubMirror"] = "gh-proxy.com",
        ["GitHubAuto"] = "Smart selection",
        ["GitHubGhProxyOrg"] = "gh-proxy.org",
        ["GitHubGhProxyNet"] = "ghproxy.net",
        ["GitHubGhFastTop"] = "ghfast.top",
        ["TestLatency"] = "Test latency",
        ["LatencyTesting"] = "Testing...",
        ["LatencyTimeout"] = "Timeout",
        ["LatencyUnavailable"] = "Unavailable",
        ["LatencyCanceled"] = "Canceled",
        ["System"] = "System",
        ["Light"] = "Light",
        ["Dark"] = "Dark",
        ["FollowSystem"] = "Follow system",
        ["SimplifiedChinese"] = "Simplified Chinese",
        ["English"] = "English",
        ["Vanilla"] = "Vanilla",
        ["UnknownBuild"] = "Unknown build · vanilla only",
        ["Local"] = "Local",
        ["External"] = "External",
        ["Pinned"] = "Pinned",
        ["NeedsAttentionFilter"] = "Needs attention",
        ["PinMod"] = "Pin Mod",
        ["UnpinMod"] = "Unpin Mod",
        ["TakeOverMod"] = "Take over external Mod",
        ["RepairMod"] = "Repair Mod",
        ["AcceptCurrentFiles"] = "Accept current files",
        ["ReimportLocalMod"] = "Re-import local Mod",
        ["ExternalModReadOnly"] = "External Mods are read-only until they are taken over.",
        ["UnpinBeforeUninstall"] = "Unpin this Mod before uninstalling it.",
        ["ModHealthHealthy"] = "Healthy",
        ["ModHealthCriticalFileMissing"] = "Critical file missing",
        ["ModHealthModifiedFile"] = "Modified file",
        ["ModHealthExtraFile"] = "Extra file",
        ["ModHealthUnmanagedExternal"] = "Unmanaged external",
        ["ModHealthIndeterminate"] = "Integrity unknown",
        ["UnusedDependencies"] = "Unused dependencies",
        ["UnusedDependencyCountFormat"] = "{0} unused dependencies can be reviewed for cleanup.",
        ["Installed"] = "Installed",
        ["Disabled"] = "Disabled",
        ["NoMods"] = "No managed Mods",
        ["NoSnapshots"] = "No snapshots",
        ["CreateSnapshot"] = "Create snapshot",
        ["Restore"] = "Restore",
        ["StatusChecking"] = "Checking instances...",
        ["StatusReady"] = "Ready",
        ["ErrorDirectoryNotFound"] = "A directory was not found",
        ["ErrorFileNotFound"] = "A file was not found",
        ["ErrorFileLocked"] = "A file is being used by another process",
        ["ErrorAccessDenied"] = "Access was denied",
        ["ErrorNetworkRequestFailed"] = "The network request failed",
        ["ErrorNetworkTimeout"] = "The network request timed out",
        ["ErrorDataInvalid"] = "The data is invalid or malformed",
        ["ErrorVerificationFailed"] = "File verification failed",
        ["OperationFailed"] = "Operation failed"
        ,["OperationComplete"] = "Operation completed"
        ,["SelectLoader"] = "Select a Loader first."
        ,["SelectMod"] = "Select a Mod first."
        ,["SelectSnapshot"] = "Select a snapshot first."
        ,["SelectSpeedrunTemplate"] = "Select a speedrun template first."
        ,["SnapshotNameRequired"] = "Enter a snapshot name."
        ,["LoaderConflict"] = "Conflicting Loader files require manual repair."
        ,["RepairBeforeSwitch"] = "Repair the current Loader before switching."
        ,["LoaderSwitchBlockedByMods"] = "Uninstall every managed Mod, including disabled and local Mods, before switching Loaders. The current Loader and Mod files were left unchanged."
        ,["LoaderUninstallBlockedByMods"] = "Uninstall every managed Mod, including disabled and local Mods, before uninstalling the Loader. The current Loader and Mod files were left unchanged."
        ,["LoaderRepairPackageUnavailable"] = "The installed Loader package is not available in the current catalog."
        ,["LoaderRepairIdentityUnknown"] = "The missing Loader receipt cannot be recovered because its exact Loader package could not be identified from the installed Mods."
        ,["LoaderReceiptRecoveryAvailable"] = "The Loader receipt is missing, but the installed managed Mods identify it. Choose Repair to restore the Loader."
        ,["ExternalLoaderBlocked"] = "An unmanaged Loader is present. To protect the original game files, Crystalfly will not overwrite or repair it. Download or create a clean instance before installing a Loader."
        ,["LoaderRequired"] = "Install the required Loader first."
        ,["WrongLoader"] = "This Mod requires another Loader"
        ,["UpdateRequired"] = "Update is required before reinstalling"
        ,["CloseGameFirst"] = "Close every Hollow Knight process before changing this instance."
        ,["NoVanillaSource"] = "No clean vanilla instance matches this template."
        ,["SpeedrunNeedsVerification"] = "Dedicated copy created. Run verification before an official attempt."
        ,["SpeedrunUnverified"] = "Dedicated copy created as unverified because the catalog has no trusted file manifest."
        ,["InstallOrSwitch"] = "Install or switch"
        ,["Repair"] = "Repair"
        ,["Uninstall"] = "Uninstall"
        ,["EnableDisable"] = "Enable / disable"
        ,["Install"] = "Install"
        ,["AvailableMods"] = "Available Mods"
        ,["InstalledMods"] = "Installed Mods"
        ,["ModPresets"] = "Mod Packs"
        ,["ModPresetsHint"] = "Capture the current enabled Mod set, then append or exactly apply the Mod Pack to this instance."
        ,["ModPacks"] = "Mod Packs"
        ,["ModPacksHint"] = "Create, import, share, and apply compact Mod collections without expanding every detail at once."
        ,["LocalModPacks"] = "Local Mod Packs"
        ,["SearchModPacks"] = "Search Mod Packs"
        ,["CreateModPack"] = "New Mod Pack"
        ,["CreateModPackHint"] = "Capture the Mods currently enabled in this instance. Choose how the Mod Pack should be applied later."
        ,["CopyModPackHint"] = "Enter a name for the copied Mod Pack."
        ,["NoMatchingModPacks"] = "No matching Mod Packs. Create one from the current instance or import JSON."
        ,["ModPackSummary"] = "Compatibility and application summary"
        ,["GameBuild"] = "Game build"
        ,["ModCount"] = "Mod count"
        ,["ViewModPackContents"] = "View Mod list"
        ,["SearchModPackContents"] = "Search this Mod list"
        ,["NoModPackSelected"] = "Select a Mod Pack"
        ,["NoModPackSelectedHint"] = "Choose one on the left to review compatibility and apply it to the current instance."
        ,["ImportSharedPresetHint"] = "Enter the 12-character share code. The imported Mod Pack remains a local JSON document."
        ,["PresetName"] = "Mod Pack name"
        ,["PresetMode"] = "Apply mode"
        ,["PresetModeAppend"] = "Append"
        ,["PresetModeExact"] = "Exact"
        ,["CreatePreset"] = "Create from current Mods"
        ,["RecapturePreset"] = "Recapture"
        ,["CopyPreset"] = "Copy Mod Pack"
        ,["DeletePreset"] = "Delete Mod Pack"
        ,["ImportPreset"] = "Import JSON"
        ,["ExportPreset"] = "Export JSON"
        ,["SharePreset"] = "Share Mod Pack"
        ,["PresetShareCode"] = "12-character share code"
        ,["ImportSharedPreset"] = "Import share code"
        ,["ApplyPreset"] = "Apply Mod Pack"
        ,["RestorePresetState"] = "Restore pre-apply state"
        ,["PresetEntries"] = "Mod Pack entries"
        ,["NoPresetsAction"] = "No Mod Packs. Create one from the current enabled Mods."
        ,["PresetNameRequired"] = "Enter a Mod Pack name."
        ,["PresetNoChanges"] = "This Mod Pack has no automatic changes to apply."
        ,["PresetExported"] = "Mod Pack exported."
        ,["PresetShared"] = "Mod Pack share created."
        ,["PresetShareLink"] = "Share link"
        ,["PresetShareLinkCopied"] = "Mod Pack share link copied."
        ,["PresetTargetInstance"] = "Target instance"
        ,["PresetJsonFiles"] = "JSON files"
        ,["PresetJsonFileRequired"] = "Choose a JSON Mod Pack file."
        ,["ConfirmDeletePresetTitle"] = "Delete Mod Pack?"
        ,["ConfirmDeletePresetMessage"] = "The local Mod Pack definition will be removed. Installed Mods are not changed."
        ,["ConfirmApplyPresetTitle"] = "Apply Mod Pack?"
        ,["ConfirmApplyPresetMessage"] = "Review installs, enablement changes, disabled Mods, and unresolved local entries before adding the plan to the download queue."
        ,["PresetStepInstall"] = "Install"
        ,["PresetStepEnable"] = "Enable"
        ,["PresetStepDisable"] = "Disable"
        ,["PresetStepUnresolved"] = "Unresolved"
        ,["PresetStepBlocked"] = "Blocked"
        ,["PresetStateSatisfied"] = "Ready"
        ,["PresetStatePending"] = "Will change"
        ,["PresetStateUnresolved"] = "Needs local file"
        ,["PresetStateBlocked"] = "Blocked"
        ,["SnapshotName"] = "Snapshot name"
        ,["Template"] = "Template"
        ,["EnvironmentName"] = "Environment name"
        ,["LocalModPath"] = "Local ZIP or DLL path"
        ,["ImportLocalMod"] = "Import local Mod"
        ,["LocalModPathRequired"] = "Choose an existing local ZIP or DLL."
        ,["LocalModType"] = "Only ZIP and DLL Mod imports are supported."
        ,["Cancel"] = "Cancel"
        ,["Save"] = "Save"
        ,["CustomCatalogSources"] = "Custom catalog sources"
        ,["CustomModLinks"] = "Custom ModLinks"
        ,["CustomModLinksHint"] = "Optional full replacement for HK ModLinks. Bind it to one exact game build and Modding API Loader. Custom sources are unverified. Clear the URL to restore the official source."
        ,["CustomModLinksInvalid"] = "Enter an HTTPS URL and select an exact game build and Modding API Loader."
        ,["CustomModLinksRemote"] = "Custom ModLinks · remote"
        ,["CustomModLinksCached"] = "Custom ModLinks · cached"
        ,["CustomModLinksFailed"] = "Custom ModLinks · unavailable"
        ,["UnverifiedSource"] = "Unverified source"
        ,["SelectVersionRootTitle"] = "Select Hollow Knight version root"
        ,["SelectModPackageTitle"] = "Select a Mod package"
        ,["ModFileType"] = "Hollow Knight Mod"
        ,["Confirm"] = "Continue"
        ,["ConfirmLoaderUninstallTitle"] = "Uninstall Loader?"
        ,["ConfirmLoaderUninstallMessage"] = "Managed Loader files will be removed from the selected instance."
        ,["ConfirmModUninstallTitle"] = "Uninstall Mod?"
        ,["ConfirmModUninstallMessage"] = "The selected managed Mod will be removed from this instance."
        ,["ConfirmSnapshotRestoreTitle"] = "Restore snapshot?"
        ,["ConfirmSnapshotRestoreMessage"] = "Current instance save data will be replaced with the selected snapshot."
        ,["DeleteSnapshot"] = "Delete snapshot"
        ,["ConfirmSnapshotDeleteTitle"] = "Delete snapshot?"
        ,["ConfirmSnapshotDeleteMessage"] = "The selected save snapshot will be permanently deleted."
        ,["NoInstancesAction"] = "No instances found. Choose a version root in Settings or refresh."
        ,["NoLoadersAction"] = "No compatible Loaders. Refresh after checking the selected build."
        ,["NoAvailableModsAction"] = "No compatible Mods. Check catalog sources in Settings."
        ,["NoInstalledModsAction"] = "No managed Mods are installed in this instance."
        ,["NoSnapshotsAction"] = "No snapshots. Enter a name above to create the first one."
        ,["NoSpeedrunTemplatesAction"] = "No templates available. Check catalog sources in Settings."
        ,["NoDownloadBuildsAction"] = "No builds available. Check catalog sources in Settings."
        ,["SearchGameVersions"] = "Search versions or Manifest IDs"
        ,["OtherHistoricalVersion"] = "Other historical version"
        ,["HistoricalManifestTitle"] = "Download historical version"
        ,["HistoricalManifestHint"] = "Enter a Hollow Knight Windows Depot Manifest ID."
        ,["HistoricalManifestId"] = "Manifest ID"
        ,["HistoricalInstanceName"] = "Instance name"
        ,["HistoricalManifestKnown"] = "Verified catalog build: {0}"
        ,["HistoricalManifestUnverified"] = "Unverified historical version · vanilla only"
        ,["InvalidHistoricalManifest"] = "Enter a non-zero unsigned Manifest ID."
        ,["UnverifiedHistoricalBuild"] = "Unverified historical version"
        ,["SteamLoginRequired"] = "Sign in to Steam before queuing a download."
        ,["OpenSettings"] = "Open settings"
        ,["SelectInstance"] = "Select instance"
        ,["InstanceSettings"] = "Instance settings"
        ,["Back"] = "Back"
        ,["CloneInstance"] = "Clone instance"
        ,["CloneInstanceName"] = "New instance name"
        ,["CopySuffix"] = "Copy"
        ,["FavoriteInstance"] = "Favorite instance"
        ,["UnfavoriteInstance"] = "Remove from favorites"
        ,["InstanceShortcuts"] = "Shortcuts"
        ,["InstanceFolder"] = "Instance folder"
        ,["SaveFolder"] = "Save folder"
        ,["ModFolder"] = "Mod folder"
        ,["InstanceActions"] = "Instance actions"
        ,["RenameInstance"] = "Rename instance"
        ,["RenameInstanceHint"] = "Renaming also changes the instance folder name."
        ,["RenameBlockedDownloads"] = "Cancel or finish downloads for this instance before renaming it."
        ,["RenameBlockedTransactions"] = "Resolve unfinished file transactions before renaming this instance."
        ,["CompleteInstanceFiles"] = "Complete files"
        ,["CompleteInstanceFilesHint"] = "Restore missing files and damaged core files from this build's Steam manifest. Extra files, Loader, Mods and saves are kept."
        ,["DeleteInstance"] = "Delete instance"
        ,["DeleteInstanceTitle"] = "Permanently delete instance"
        ,["DeleteInstanceMessage"] = "The game directory, Loader, Mods, isolated saves and snapshots will be permanently deleted."
        ,["PermanentDeleteWarning"] = "This action permanently deletes the instance and cannot be undone."
        ,["DeleteBlockedGameRunning"] = "Close Hollow Knight before deleting this instance."
        ,["DeleteBlockedDownloads"] = "Cancel or finish downloads for this instance before deleting it."
        ,["DeleteBlockedTransactions"] = "Resolve unfinished file transactions before deleting this instance."
        ,["DeleteCleanupPending"] = "Instance deleted. Pending files will be cleaned on next start."
        ,["DeleteRecoveryNeedsAttention"] = "An unfinished instance deletion needs attention."
        ,["CloneNameRequired"] = "Enter a name for the cloned instance."
        ,["CloneVanillaOnly"] = "Clone a vanilla instance so Loader and Mod state stay independent."
        ,["LoadNormaliserSeconds"] = "Load normaliser seconds"
        ,["SpeedrunTemplateMissing"] = "The speedrun template is no longer available."
        ,["SpeedrunBuildMissing"] = "The speedrun game build is no longer available."
        ,["SpeedrunManifestMissing"] = "The speedrun file manifest is no longer available."
        ,["SpeedrunVerified"] = "Official speedrun pre-launch integrity check passed."
        ,["SpeedrunVerifiedWithWarnings"] = "Technical validation passed. Review the category rule warnings before starting."
        ,["SpeedrunVerificationFailed"] = "Official speedrun pre-launch integrity check failed; launch is blocked."
        ,["SpeedrunUnverifiedReport"] = "Unverified speedrun report generated."
        ,["SpeedrunOpenReport"] = "Open report"
        ,["SpeedrunCopyReportPath"] = "Copy report path"
        ,["SpeedrunReportPathCopied"] = "Report path copied."
        ,["SpeedrunReportPathMissing"] = "The speedrun report is no longer available."
        ,["RecoveryNeedsAttention"] = "A file transaction needs manual attention before launch."
        ,["AdvancedLocalLoader"] = "Advanced local Loader import"
        ,["LocalLoaderManifestPath"] = "Crystalfly Loader manifest (.json)"
        ,["LocalLoaderManifestRequired"] = "Choose an existing Crystalfly Loader manifest."
        ,["SelectLoaderManifestTitle"] = "Select Crystalfly Loader manifest"
        ,["LoaderManifestFileType"] = "Crystalfly Loader manifest"
        ,["ImportLocalLoader"] = "Import local Loader"
        ,["Unverified"] = "Unverified"
        ,["UnverifiedLocalLoader"] = "Local Loader · unverified"
        ,["VerifiedCatalogLoader"] = "Catalog Loader · verified package"
        ,["FilterMods"] = "Search Mods"
        ,["FilterAll"] = "All statuses"
        ,["Enabled"] = "Enabled"
        ,["Updates"] = "Updates"
        ,["Update"] = "Update"
        ,["UpdateAvailable"] = "Update available"
        ,["SelectedMods"] = "Mods selected"
        ,["Information"] = "Information"
        ,["OpenFolder"] = "Open folder"
        ,["SelectMultiple"] = "Select multiple"
        ,["SelectAll"] = "Select all"
        ,["ClearSelection"] = "Clear selection"
        ,["BatchActions"] = "Batch actions"
        ,["BatchEnable"] = "Enable selected"
        ,["BatchDisable"] = "Disable selected"
        ,["BatchUninstall"] = "Uninstall selected"
        ,["Enable"] = "Enable"
        ,["Disable"] = "Disable"
        ,["Missing"] = "Missing"
        ,["NeedsRepair"] = "Needs repair"
        ,["DependencyProblem"] = "Dependency problem"
        ,["NeedsAttention"] = "Needs attention"
        ,["LaunchBlocked"] = "Launch is blocked until the failed preflight checks are resolved."
        ,["NoUpdateAvailable"] = "No catalog update is available for the selected Mod."
        ,["ReverseDependencies"] = "Dependent Mods must be removed or included first"
        ,["RefreshFailed"] = "Refresh failed"
        ,["GameFiles"] = "Game files"
        ,["LoaderStatus"] = "Loader state"
        ,["LogFiles"] = "Log files"
        ,["NoLogs"] = "No supported log files were found for this instance."
        ,["RefreshLogs"] = "Refresh logs"
        ,["ConfirmBulkUninstallTitle"] = "Uninstall selected Mods?"
        ,["ConfirmBulkUninstallMessage"] = "The selected managed Mods will be removed from this instance."
        ,["CannotUninstallDependents"] = "These installed Mods depend on the selection:"
        ,["DependencyImpact"] = "Dependency impact"
        ,["DependencyList"] = "List"
        ,["DependencyGraph"] = "Dependency graph"
        ,["DependencyGraphFocus"] = "Selected Mod relationships"
        ,["DependencyGraphAll"] = "All installed Mods"
        ,["DependencyRelationshipUnknown"] = "Relationship unknown"
        ,["RepairDependencies"] = "Repair dependencies"
        ,["WillDelete"] = "Will delete"
        ,["DependenciesWillBeMissing"] = "Dependencies will be missing"
        ,["WillReEnable"] = "Will re-enable"
        ,["WillDownloadAndInstall"] = "Will download and install"
        ,["CannotRepair"] = "Cannot repair"
        ,["Target"] = "Target"
        ,["Unresolved"] = "Unresolved"
        ,["GameVersions"] = "Game versions"
        ,["ModMarket"] = "Mod Market"
        ,["MarketTitle"] = "Discover Mods"
        ,["MarketHint"] = "Browse the official HK ModLinks catalog and install a compatible release into an instance."
        ,["MarketSearch"] = "Search Mods"
        ,["MarketBuild"] = "Game build"
        ,["MarketLoader"] = "Loader"
        ,["MarketSource"] = "Source"
        ,["MarketTag"] = "Tag"
        ,["ActivityAll"] = "All activity"
        ,["RecentlyAdded"] = "Recently added"
        ,["RecentlyUpdated"] = "Recently updated"
        ,["MarketEmpty"] = "No Mods match the current filters."
        ,["ViewDetails"] = "View details"
        ,["BackToMarket"] = "Back to Mod Market"
        ,["Authors"] = "Authors"
        ,["Tags"] = "Tags"
        ,["Integrations"] = "Integrations"
        ,["SupportedBuilds"] = "Supported builds"
        ,["Dependencies"] = "Dependencies"
        ,["QueueDetails"] = "Task details"
        ,["Source"] = "Source"
        ,["Repository"] = "Repository"
        ,["ModDetails"] = "Mod details"
        ,["CurrentVersion"] = "Current version"
        ,["LatestVersion"] = "Latest version"
        ,["InstallHistory"] = "Install history"
        ,["InstalledAt"] = "Installed at"
        ,["ModifiedFiles"] = "Modified files"
        ,["FileConflicts"] = "File conflicts"
        ,["CheckAllForUpdates"] = "Check all for updates"
        ,["UpdatesAvailable"] = "Updates available"
        ,["ConflictWith"] = "Conflicts with"
        ,["ExpandNode"] = "Expand node"
        ,["CollapseNode"] = "Collapse node"
        ,["Readme"] = "README"
        ,["LatestReleaseNotes"] = "Latest release notes"
        ,["ReinstallMod"] = "Reinstall Mod"
        ,["GlobalSettings"] = "Global settings"
        ,["DeleteGlobalSettings"] = "Delete global settings"
        ,["OpenLogs"] = "Open logs"
        ,["ContentRemote"] = "Live content"
        ,["ContentCached"] = "Cached content"
        ,["ContentUnavailable"] = "Content unavailable"
        ,["OfficialEnglishDescription"] = "Official English description"
        ,["Issues"] = "Issues"
        ,["InstallModTitle"] = "Install Mod"
        ,["InstallToInstance"] = "Choose target instance"
        ,["NoInstallTargets"] = "No instances are available for this Mod."
        ,["InstallSelectedMod"] = "Install selected Mod"
        ,["MarketWillInstallLoader"] = "Will install {0} first"
        ,["MarketWrongLoaderBlocked"] = "Another Loader is installed"
        ,["MarketDriftedBlocked"] = "Loader files have drifted and must be repaired first"
        ,["MarketIncompatibleBlocked"] = "This game build is not compatible with the Mod and its dependencies"
        ,["OfficialSpeedrunModBlocked"] = "Official speedrun instances cannot install Mods"
        ,["AboutSpeedrunSources"] = "Speedrun sources"
        ,["AboutSpeedrunSourcesDescription"] = "RuntimePatches follows HK Speedrunning and HK-Resources guidance. AssemblyPatches v1.0.2 release binaries are pinned by ZIP and DLL SHA-256 because the repository source does not fully reproduce those published binaries."
        ,["ExternalLoader"] = "External"
        ,["HKModLinks"] = "HK ModLinks"
        ,["HKModLinksHint"] = "Official Mod catalog · read-only"
        ,["CatalogRemote"] = "Remote"
        ,["CatalogCached"] = "Cached"
        ,["CatalogFailed"] = "Failed"
        ,["DownloadQueue"] = "Download queue"
        ,["DownloadQueueHint"] = "Downloads continue in the background. Instance files are changed only after the game exits."
        ,["DownloadQueueEmpty"] = "No downloads yet. Choose a game version or install a Mod from the market."
        ,["AddToDownloadQueue"] = "Add to download queue"
        ,["AddedToDownloadQueue"] = "Added to download queue"
        ,["QueueTaskAlreadyExists"] = "This task is already in the download queue"
        ,["RequiredComponents"] = "Required components"
        ,["MainMod"] = "Main Mod"
        ,["Dependency"] = "Dependency"
        ,["WillInstall"] = "Will install"
        ,["WillUpdate"] = "Will update"
        ,["InstallationPlan"] = "Installation plan"
        ,["ConfirmCloseDownloadsTitle"] = "Close with unfinished downloads?"
        ,["ConfirmCloseDownloadsMessage"] = "Active transfers will stop at a safe boundary. Unfinished and failed tasks will be saved and can resume after restart."
        ,["QueueTarget"] = "Target"
        ,["QueueRetry"] = "Retry"
        ,["QueueRetryCount"] = "Retries: {0}"
        ,["QueueRetryAll"] = "Retry all"
        ,["QueuePauseAll"] = "Pause all"
        ,["QueueResumeAll"] = "Resume all"
        ,["QueueClearCompleted"] = "Clear completed"
        ,["QueueCopyError"] = "Copy error"
        ,["QueueCompletedFormat"] = "{0} finished downloading"
        ,["DownloadErrorOffline"] = "Offline"
        ,["DownloadErrorNetwork"] = "Network"
        ,["DownloadErrorVerification"] = "Verification"
        ,["DownloadErrorPermission"] = "Permission"
        ,["DownloadErrorOther"] = "Other"
        ,["QueueStatePending"] = "Pending"
        ,["QueueStateRunning"] = "Running"
        ,["QueueStateTransferring"] = "Downloading"
        ,["QueueStateWaitingForGameExit"] = "Waiting for game to exit"
        ,["QueueStateWaitingForSteamLogin"] = "Waiting for Steam sign-in"
        ,["QueueStateInstalling"] = "Installing"
        ,["QueueStateCompleted"] = "Completed"
        ,["QueueStateFailed"] = "Failed"
        ,["QueueStateBlocked"] = "Blocked"
        ,["QueueStateCanceled"] = "Canceled"
        ,["QueueStageStarting"] = "Starting"
        ,["QueueStageRetrying"] = "Retrying"
        ,["QueueStageCached"] = "Using cached package"
        ,["QueueStageSatisfied"] = "Already installed"
        ,["CloseWithDownloadsTitle"] = "Close while downloads are active?"
        ,["CloseWithDownloadsMessage"] = "Active downloads will be canceled at the next safe boundary and restored to the queue on the next launch."
        ,["ActiveDownloads"] = "{0} active downloads"
        ,["ExternalCommandTitle"] = "Review external command"
        ,["ExternalCommandMessage"] = "Another app or link requested this action. Review the exact target before running it."
        ,["RunCommand"] = "Run command"
        ,["ProtocolDownloadMod"] = "Download and install a Mod"
        ,["ProtocolReinstallAllMods"] = "Reinstall all eligible managed Mods"
        ,["ProtocolResetApplicationSettings"] = "Reset Crystalfly settings"
        ,["ProtocolUseOfficialModLinks"] = "Switch to official HK ModLinks"
        ,["ProtocolUseCustomModLinks"] = "Switch to a custom ModLinks source"
        ,["ProtocolDeleteModSettings"] = "Delete one Mod's global settings"
        ,["ProtocolDeleteAllModSettings"] = "Delete all official Mod global settings"
        ,["ProtocolLaunchInstance"] = "Launch an instance with normal preflight checks"
        ,["ProtocolOpenModLocation"] = "Open the installed Mod folder"
        ,["ProtocolImportPresetShare"] = "Import a shared Mod Pack into the selected instance"
        ,["ProtocolNoModsToReinstall"] = "No eligible managed Mods are available to reinstall."
        ,["ProtocolSettingsReset"] = "Crystalfly settings were reset. Choose a version root to continue."
        ,["ProtocolNoGlobalSettings"] = "No matching global settings files were found."
        ,["ProtocolOpenFolderFailed"] = "Windows did not open the Mod folder."
        ,["InvalidExternalCommand"] = "The external command was rejected"
        ,["ExternalCommandBusy"] = "Finish the current Crystalfly operation before running an external command."
        ,["ExternalCommandGameRunning"] = "Close Hollow Knight before running an external command."
        ,["ExternalCommandDownloadsActive"] = "Finish or cancel active downloads before changing application sources or settings."
        ,["ExternalCommandClosing"] = "Crystalfly is closing; the external command was not started."
        ,["ApplicationUpdates"] = "Application updates"
        ,["ApplicationUpdatesHint"] = "Check the signed stable channel once per day. Downloads use the selected GitHub route."
        ,["CheckForUpdates"] = "Check automatically"
        ,["CheckNow"] = "Check now"
        ,["CurrentVersionFormat"] = "Current version: {0}"
        ,["UpdateChecksDisabled"] = "Automatic update checks are disabled"
        ,["UpdateCheckNotDue"] = "Checked within the last 24 hours"
        ,["ApplicationUpToDate"] = "Crystalfly is up to date"
        ,["UpdateVersionSkipped"] = "This version is skipped"
        ,["ApplicationUpdateAvailableFormat"] = "Version {0} is available"
        ,["UpdateCheckFailed"] = "Update check failed"
        ,["UpdateManifestUnavailable"] = "No signed update manifest is published for the latest release"
        ,["DownloadingApplicationUpdate"] = "Downloading and verifying update..."
        ,["ApplicationUpdateStarting"] = "Starting update helper..."
        ,["ApplicationUpdateTitle"] = "Crystalfly update available"
        ,["ApplicationUpdateVersionFormat"] = "Version {0}"
        ,["UpdateNow"] = "Update now"
        ,["Later"] = "Later"
        ,["SkipThisVersion"] = "Skip this version"
        ,["ProtocolRegistration"] = "crystalfly:// protocol"
        ,["ProtocolRegistrationHint"] = "The installer registers links used by Mod Pack shares and external commands."
        ,["ProtocolRegistered"] = "Registered"
        ,["ProtocolNotRegistered"] = "Not registered"
        ,["LatestBuild"] = "Latest"
        ,["GameDirectories"] = "Game directories"
        ,["GameDirectoriesHint"] = "Choose a root, then select one of its Hollow Knight instances."
        ,["AddGameDirectory"] = "Add directory"
        ,["RemoveGameDirectory"] = "Remove directory"
        ,["RefreshGameDirectories"] = "Refresh directories"
        ,["ScanGameDirectories"] = "Scan game directories"
        ,["ScanGameDirectoriesProgress"] = "Scanning... {0} directories checked"
        ,["NoGameDirectories"] = "No game directories are registered."
        ,["NoGameDirectoryCandidates"] = "No Hollow Knight installation was found in that directory."
        ,["SelectGameDirectory"] = "Select a game directory"
        ,["GameDirectoryDiscoveryTitle"] = "Find Hollow Knight installations"
        ,["GameDirectoryDiscoveryHint"] = "Scan Steam libraries or add a folder. Nothing is registered until you confirm it."
        ,["ConfirmAddDirectories"] = "Add selected"
        ,["SkipForNow"] = "Skip for now"
        ,["ScanPending"] = "Pending"
        ,["Scanning"] = "Scanning"
        ,["ScanReady"] = "Ready"
        ,["ScanFailed"] = "Unavailable"
        ,["InvalidGameDirectory"] = "The game directory has no valid parent folder."
        ,["SteamDirectoryRiskTitle"] = "Manage the Steam installation?"
        ,["SteamDirectoryRiskHint"] = "Direct management can conflict with Steam updates or file verification. Migration is recommended."
        ,["MigrateInstance"] = "Migrate instance"
        ,["AcceptSteamRisk"] = "Manage in place"
        ,["SelectMigrationTarget"] = "Select a non-Steam destination"
        ,["MigrationTargetMustNotBeSteam"] = "The migration target must be a non-Steam game directory."
        ,["MigrationBlockedByDownload"] = "Finish or cancel this instance's download tasks before migrating it."
        ,["DeleteSteamInstanceTitle"] = "Remove the Steam installation?"
        ,["DeleteSteamInstanceHint"] = "You can only remove it from Crystalfly, or permanently delete the game directory."
        ,["PermanentlyDeleteDirectory"] = "Delete directory"
        ,["UnregisterOnly"] = "Remove from Crystalfly"
    };

    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["NavLaunch"] = "启动",
        ["NavVersions"] = "实例",
        ["NavManage"] = "管理",
        ["NavSpeedrun"] = "速通",
        ["NavDownloads"] = "下载",
        ["NavSettings"] = "设置",
        ["WindowMinimize"] = "最小化",
        ["WindowMaximize"] = "最大化 / 还原",
        ["WindowClose"] = "关闭",
        ["Ready"] = "准备就绪",
        ["ReadyHint"] = "当前实例已通过启动前检查。",
        ["NoInstance"] = "未选择实例",
        ["ChooseRoot"] = "请选择版本根目录以发现空洞骑士实例。",
        ["LaunchGame"] = "启动游戏",
        ["LaunchIssues"] = "启动问题",
        ["LaunchIssueCountFormat"] = "{0} 个启动问题",
        ["LaunchWarningTitle"] = "检查启动问题",
        ["LaunchWarningMessage"] = "检测到模组完整性或前置问题，请确认后再继续。",
        ["LaunchBlockedTitle"] = "启动已阻止",
        ["ForceLaunch"] = "强制启动",
        ["DoNotRemindLaunchWarnings"] = "这些问题及文件哈希不变时不再提醒",
        ["LaunchIssueExecutableMissing"] = "游戏主程序缺失",
        ["LaunchIssueGameAlreadyRunning"] = "空洞骑士已经在运行",
        ["LaunchIssueUnknownBuild"] = "游戏构建与 Loader 组合不受支持",
        ["LaunchIssueLoaderConflict"] = "检测到冲突的 Loader 文件",
        ["LaunchIssueLoaderDrifted"] = "Loader 文件已经漂移",
        ["LaunchIssueMissingDependency"] = "缺少必要的模组前置",
        ["LaunchIssueDisabledDependency"] = "必要的模组前置已停用",
        ["LaunchIssueTransactionNeedsAttention"] = "文件事务需要处理",
        ["LaunchIssueLocalLowNotReady"] = "实例隔离存档尚未就绪",
        ["LaunchIssueModCriticalFileMissing"] = "模组必要文件缺失",
        ["LaunchIssueModModifiedFile"] = "模组文件已被修改",
        ["LaunchIssueModExtraFile"] = "模组目录包含额外文件",
        ["LaunchIssueExternalMod"] = "发现未接管的外部模组",
        ["LaunchIssueModIndeterminate"] = "暂时不能判定模组完整性",
        ["Refresh"] = "刷新",
        ["ManageInstance"] = "实例设置",
        ["LoaderFiles"] = "游戏与 Loader 文件",
        ["ModDependencies"] = "Mod 依赖关系",
        ["SaveIsolation"] = "存档隔离",
        ["Complete"] = "完整",
        ["NoConflicts"] = "无冲突",
        ["Mounted"] = "已就绪",
        ["Instances"] = "实例",
        ["InstancesHint"] = "所选根目录中的已知版本与完整复制环境。",
        ["SearchInstances"] = "搜索实例",
        ["Overview"] = "概览",
        ["Loader"] = "Loader",
        ["Mods"] = "Mods",
        ["Snapshots"] = "存档快照",
        ["Logs"] = "日志",
        ["Config"] = "配置",
        ["ConfigHint"] = "编辑实例的游戏配置文件（AppConfig.ini）。视频、音频、语言与键位存储在别处，无法在此编辑。",
        ["Accessibility"] = "无障碍",
        ["ReducedCameraShake"] = "减弱镜头抖动",
        ["ReducedControllerRumble"] = "减弱手柄震动",
        ["AdvancedConfig"] = "高级键值",
        ["AdvancedConfigHint"] = "直接编辑任意段、键或值，未知字段会被保留。",
        ["AddEntry"] = "添加条目",
        ["RemoveEntry"] = "删除",
        ["SaveConfig"] = "保存",
        ["ResetConfig"] = "重置",
        ["ConfigSaved"] = "配置已保存",
        ["ConfigSection"] = "段",
        ["ConfigKey"] = "键",
        ["ConfigValue"] = "值",
        ["ConfigLocked"] = "请关闭游戏后再编辑配置。",
        ["CurrentSave"] = "当前实例存档",
        ["EditSave"] = "编辑存档",
        ["SaveSlot"] = "存档槽",
        ["NoSaveSlots"] = "此实例还没有存档文件。",
        ["SpeedrunTitle"] = "正式速通环境",
        ["SpeedrunHint"] = "创建专用验证副本，不修改日常实例。",
        ["SpeedrunComingSoon"] = "仍在开发中",
        ["SpeedrunComingSoonHint"] = "正式速通环境正在按直接插件安装方式重新设计。",
        ["SpeedrunCreate"] = "创建环境",
        ["SpeedrunInstances"] = "速通环境",
        ["SpeedrunInstancesHint"] = "使用固定 RuntimePatches 资源的独立完整副本。",
        ["SpeedrunNoInstance"] = "选择一个速通环境，或创建新环境。",
        ["SpeedrunTemplateExpired"] = "模板已过期，正式速通前请重新创建环境。",
        ["SpeedrunTechnicalReady"] = "RuntimePatches 环境",
        ["SpeedrunNeedsRebuild"] = "该环境不是当前 RuntimePatches 模板。",
        ["SpeedrunConfiguration"] = "RuntimePatches 配置",
        ["SpeedrunConfigurationInvalid"] = "RuntimePatches 配置无效",
        ["SpeedrunFeatureWarnings"] = "计时包含开场动画时必须关闭 FasterIntroSkip；MiniSaveStates 仅限规则明确允许的单关，运行中不得加载。开始前请自行确认具体分类规则。",
        ["SpeedrunFeatureUnavailable"] = "当前游戏版本不可用",
        ["SpeedrunEnvironmentName"] = "环境名称",
        ["SpeedrunSelectVanillaSource"] = "选择干净的 Vanilla 源实例",
        ["SpeedrunVerifyAndLaunch"] = "校验并启动",
        ["SpeedrunReinstall"] = "重新安装 RuntimePatches",
        ["SpeedrunEnvironmentTab"] = "环境",
        ["SpeedrunActivityTab"] = "赛况",
        ["SpeedrunGameHollowKnight"] = "空洞骑士",
        ["SpeedrunGameSilksong"] = "空洞骑士：丝之歌",
        ["SpeedrunActivityTitle"] = "成绩动态",
        ["SpeedrunActivityHint"] = "追踪 Speedrun.com 官方榜单中新验证的世界纪录与前三成绩。",
        ["SpeedrunGame"] = "游戏",
        ["SpeedrunCategory"] = "分类",
        ["SpeedrunRefresh"] = "检查新成绩",
        ["SpeedrunActivityAll"] = "全部",
        ["SpeedrunActivityLoading"] = "正在检查官方榜单…",
        ["SpeedrunActivityUnavailable"] = "暂时无法获取成绩动态。",
        ["SpeedrunActivityReady"] = "监控已建立",
        ["SpeedrunActivityCached"] = "使用榜单缓存",
        ["SpeedrunActivityUpdatedAt"] = "检查于 {0}",
        ["SpeedrunActivityPartialFailure"] = "有 {0} 个榜单检查失败，已保留原基线。",
        ["SpeedrunActivityEmpty"] = "监控已建立，后续榜单变化会显示在这里。",
        ["SpeedrunActivityWorldRecord"] = "世界纪录",
        ["SpeedrunActivityTiedWorldRecord"] = "并列世界纪录",
        ["SpeedrunActivitySecond"] = "第二名",
        ["SpeedrunActivityThird"] = "第三名",
        ["SpeedrunActivityToastWorldRecord"] = "{0} 在 {1} 刷新世界纪录：{2}",
        ["SpeedrunActivityToastTiedWorldRecord"] = "{0} 在 {1} 追平世界纪录：{2}",
        ["SpeedrunActivityToastSecond"] = "{0} 在 {1} 获得第二名：{2}",
        ["SpeedrunActivityToastThird"] = "{0} 在 {1} 获得第三名：{2}",
        ["SpeedrunRank"] = "排名",
        ["SpeedrunRunner"] = "选手",
        ["SpeedrunTime"] = "成绩",
        ["SpeedrunDate"] = "日期",
        ["SpeedrunOpenRun"] = "打开成绩",
        ["AboutSpeedrunComData"] = "Speedrun.com 成绩动态",
        ["AboutSpeedrunComDataDescription"] = "按需检查官方分类与已验证前三成绩，并在本地保存榜单基线和最近 100 条动态。",
        ["CreateEnvironment"] = "创建环境",
        ["DownloadsTitle"] = "下载",
        ["DownloadsHint"] = "Steam public 版本与已缓存安装包。",
        ["SteamAccount"] = "Steam 账号",
        ["SignInQr"] = "扫码登录",
        ["SignOut"] = "退出账号",
        ["SteamProxyDetected"] = "已检测到系统代理",
        ["SteamProxyDirect"] = "当前为直连网络",
        ["SteamConnecting"] = "正在连接 Steam……",
        ["SteamScanQr"] = "请使用 Steam 手机客户端扫码",
        ["SteamNetworkReconnecting"] = "正在重新连接 Steam……",
        ["SteamNetworkTimeout"] = "Steam 网络请求超时",
        ["SteamNetworkHttpError"] = "Steam 服务器返回 HTTP 错误",
        ["SteamNetworkDisconnected"] = "Steam 连接已中断",
        ["SteamNetworkUnavailable"] = "Steam 网络不可用",
        ["RefreshSteamNetwork"] = "重新检测 Steam 网络",
        ["SignInWithPassword"] = "账号密码登录",
        ["SwitchToPasswordLogin"] = "账号密码登录",
        ["SwitchToQrLogin"] = "改用扫码登录",
        ["SteamUsername"] = "用户名",
        ["SteamPassword"] = "密码",
        ["SteamLogin"] = "登录",
        ["SteamCredentialsRequired"] = "请输入 Steam 用户名和密码。",
        ["SteamGuardEmailTitle"] = "邮箱验证码",
        ["SteamGuardEmailMessage"] = "请输入发送到以下邮箱的验证码",
        ["SteamGuardDeviceTitle"] = "手机验证码",
        ["SteamGuardDeviceMessage"] = "请输入 Steam 手机客户端中显示的验证码。",
        ["SteamGuardCodePlaceholder"] = "Steam Guard 验证码",
        ["SteamGuardIncorrect"] = "验证码错误，请重试。",
        ["SteamDeviceConfirmationTitle"] = "确认登录",
        ["SteamDeviceConfirmationMessage"] = "请在 Steam 手机客户端中批准本次登录；也可以改为输入验证码。",
        ["SteamDeviceConfirmationAccept"] = "已在手机确认",
        ["SteamDeviceConfirmationSwitchToCode"] = "改为输入验证码",
        ["AdoptExternalContent"] = "接管外部模组与 Loader",
        ["AdoptExternalContentTitle"] = "接管外部内容",
        ["AdoptExternalContentMessage"] = "该实例有 {0} 个未托管的模组。是否接管到模组列表？游戏文件保持不变。",
        ["AdoptExternalContentMessageNoMods"] = "该实例有未托管的 Loader。是否接管到 Loader 状态？游戏文件保持不变。",
        ["AdoptExternalContentDone"] = "已接管外部模组与 Loader。",
        ["AdoptExternalContentFailed"] = "部分外部内容接管失败：",
        ["MatchToCatalog"] = "匹配到目录",
        ["MatchToCatalogTitle"] = "匹配模组到目录",
        ["MatchToCatalogMessage"] = "有多个目录模组可能匹配 \"{0}\"。请选择与已安装文件对应的那个。",
        ["MatchToCatalogDone"] = "已将该模组匹配到目录条目。",
        ["MatchToCatalogFailed"] = "无法将该模组匹配到目录：",
        ["MatchToCatalogNoMatch"] = "目录中没有与已安装文件匹配的模组。",
        ["SettingsTitle"] = "设置",
        ["SettingsGeneral"] = "常规",
        ["SettingsNetwork"] = "网络",
        ["SettingsCatalog"] = "目录源",
        ["SettingsUpdates"] = "更新",
        ["SettingsAbout"] = "关于",
        ["AboutTitle"] = "关于 Crystalfly",
        ["AboutDescription"] = "面向 Windows 的空洞骑士版本与 Mod 管理器。",
        ["OnboardingReopen"] = "查看新手引导",
        ["OnboardingSection"] = "新手入门",
        ["OnboardingSectionHint"] = "重新打开首次运行向导，了解如何导入游戏、安装 Loader 和添加 Mod。",
        ["OnboardingStepPosition"] = "第 {0} 步 / 共 {1} 步",
        ["OnboardingNext"] = "下一步",
        ["OnboardingBack"] = "上一步",
        ["OnboardingSkip"] = "跳过",
        ["OnboardingFinish"] = "开始使用",
        ["OnboardingStepWelcomeTitle"] = "欢迎使用 Crystalfly",
        ["OnboardingStepWelcomeDescription"] = "Crystalfly 用于管理空洞骑士的版本、Loader 与 Mod。这份简短的引导会带你熟悉核心操作。",
        ["OnboardingStepImportTitle"] = "找到你的游戏",
        ["OnboardingStepImportDescription"] = "Crystalfly 需要知道空洞骑士安装在哪里。打开 设置 > 游戏目录，扫描 Steam 库，或扫描全部磁盘并选择包含 hollow_knight.exe 的文件夹。",
        ["OnboardingStepSelectInstanceTitle"] = "选择实例",
        ["OnboardingStepSelectInstanceDescription"] = "每个检测到的游戏文件夹都会成为「版本」页面上的一个实例。选中即可管理它。上次选中的实例会在下次启动时自动记忆。",
        ["OnboardingStepLoaderTitle"] = "安装 Loader",
        ["OnboardingStepLoaderDescription"] = "大多数 Mod 需要 Loader。在实例的 Loader 页选择 Modding API 或 BepInEx 并安装。已导入的现有安装可以一键接管，或匹配到目录。",
        ["OnboardingStepModsTitle"] = "添加 Mod",
        ["OnboardingStepModsDescription"] = "在 下载 > Mod 市场 为所选实例下载 Mod，或导入你自己的 Mod。未托管的外部 Mod 可以接管并匹配到目录条目，从而正确解析依赖。",
        ["OnboardingStepLaunchTitle"] = "启动游戏",
        ["OnboardingStepLaunchDescription"] = "回到「启动」页面，Crystalfly 会先检查游戏文件、Loader 与 Mod 健康状况，再启动空洞骑士。按启动面板上的提示解决任何警告。",
        ["OnboardingStepExtraTitle"] = "更多可探索的功能",
        ["OnboardingStepExtraDescription"] = "「设置」页涵盖网络、目录与外观；「速通」页提供官方速通模板与实时动态。随时可从 设置 > 关于 回到本引导。",
        ["OnboardingStepFinishTitle"] = "准备就绪",
        ["OnboardingStepFinishDescription"] = "以上就是全部要点。如果遇到问题，错误面板会说明如何修复。你也可以随时从 设置 > 关于 重新查看本引导。",
        ["AboutContributors"] = "贡献者",
        ["AboutContributorValue"] = "JWST（wzxnb2333）",
        ["ProjectRepository"] = "项目仓库",
        ["OpenRepository"] = "在浏览器中打开",
        ["OpenSourceLicense"] = "开源许可证",
        ["LicenseName"] = "GPL-3.0-only",
        ["AboutDesignReferences"] = "设计与功能参考",
        ["AboutDesignReferencesDescription"] = "PCL2、Lumafly 与 Scarab 为信息架构、版本及 Mod 管理流程提供参考；未使用或包含其代码。",
        ["AboutOpenSourceComponents"] = "使用的开源组件",
        ["AboutOpenSourceComponentsDescription"] = "界面、Steam 通信、图标与 Markdown 渲染依赖以下项目；许可证请以各仓库为准。",
        ["AboutModCatalogAndTranslations"] = "Mod 目录与中文翻译",
        ["AboutModCatalogAndTranslationsDescription"] = "官方 Mod 元数据来自 HK ModLinks；Crystalfly 独立维护中文名称、说明和标签。",
        ["VersionRoot"] = "版本根目录",
        ["Browse"] = "浏览",
        ["Language"] = "语言",
        ["Theme"] = "主题",
        ["Motion"] = "动效",
        ["MotionFollowSystem"] = "跟随系统",
        ["MotionReduced"] = "减少动效",
        ["MotionOff"] = "关闭",
        ["AccentColor"] = "主题色",
        ["AccentColorHint"] = "选择界面强调色；最后一个彩色圆球可打开自定义取色器。",
        ["AccentBlue"] = "蓝色",
        ["AccentIndigo"] = "靛蓝",
        ["AccentCrystalPurple"] = "水晶紫",
        ["AccentRose"] = "玫红",
        ["AccentOrange"] = "橙色",
        ["AccentGreen"] = "绿色",
        ["AccentCyan"] = "青色",
        ["AccentCustom"] = "自定义颜色",
        ["AccentColorPickerTitle"] = "自定义主题色",
        ["AccentOriginal"] = "原颜色",
        ["AccentNew"] = "新颜色",
        ["AccentHex"] = "HEX",
        ["AccentInvalid"] = "请输入六位 HEX 颜色。",
        ["BackgroundImage"] = "背景图片",
        ["BackgroundImageHint"] = "设置全局背景，或为当前实例单独覆盖。",
        ["BackgroundScopeGlobal"] = "全局",
        ["BackgroundScopeGlobalHint"] = "编辑所有实例默认继承的背景。",
        ["BackgroundScopeInstance"] = "当前实例",
        ["BackgroundScopeInstanceHint"] = "为选中的实例编辑独立背景。",
        ["BackgroundSelect"] = "选择图片",
        ["BackgroundSelectHint"] = "选择不超过 25 MiB 的 PNG、JPEG、WebP 或 BMP 图片。",
        ["BackgroundDelete"] = "删除背景",
        ["BackgroundRestoreGlobal"] = "恢复全局",
        ["BackgroundOpacity"] = "背景不透明度",
        ["BackgroundOpacityHint"] = "仅调整背景图片本身的不透明度。",
        ["BackgroundPreviewEmpty"] = "未设置背景图片",
        ["BackgroundNoInstance"] = "未选择实例",
        ["BackgroundNotConfigured"] = "尚未设置全局背景。",
        ["BackgroundGlobalConfigured"] = "未设置独立背景的实例将继承此背景。",
        ["BackgroundInstanceInherited"] = "正在继承全局背景。",
        ["BackgroundInstanceIndependent"] = "正在使用实例独立背景。",
        ["GitHubRoute"] = "下载线路",
        ["GitHubRouteHint"] = "可手动选择线路，或由智能选择测速并在故障时自动切换。",
        ["OfflineMode"] = "离线模式",
        ["OfflineModeHint"] = "仅使用本地数据和已验证缓存；网络下载会等待关闭离线模式。",
        ["GitHubDirect"] = "GitHub 直连",
        ["GitHubMirror"] = "gh-proxy.com",
        ["GitHubAuto"] = "智能选择",
        ["GitHubGhProxyOrg"] = "gh-proxy.org",
        ["GitHubGhProxyNet"] = "ghproxy.net",
        ["GitHubGhFastTop"] = "ghfast.top",
        ["TestLatency"] = "测试延迟",
        ["LatencyTesting"] = "测试中...",
        ["LatencyTimeout"] = "超时",
        ["LatencyUnavailable"] = "不可用",
        ["LatencyCanceled"] = "已取消",
        ["System"] = "系统",
        ["Light"] = "亮色",
        ["Dark"] = "暗色",
        ["FollowSystem"] = "跟随系统",
        ["SimplifiedChinese"] = "简体中文",
        ["English"] = "English",
        ["Vanilla"] = "原版",
        ["UnknownBuild"] = "未知版本 · 仅允许原版",
        ["Local"] = "本地",
        ["External"] = "外部",
        ["Pinned"] = "已固定",
        ["NeedsAttentionFilter"] = "需要处理",
        ["PinMod"] = "固定模组",
        ["UnpinMod"] = "取消固定",
        ["TakeOverMod"] = "接管外部模组",
        ["RepairMod"] = "修复模组",
        ["AcceptCurrentFiles"] = "接受当前文件",
        ["ReimportLocalMod"] = "重新导入本地模组",
        ["ExternalModReadOnly"] = "外部模组在接管前为只读状态。",
        ["UnpinBeforeUninstall"] = "请先取消固定，再卸载此模组。",
        ["ModHealthHealthy"] = "正常",
        ["ModHealthCriticalFileMissing"] = "关键文件缺失",
        ["ModHealthModifiedFile"] = "文件已修改",
        ["ModHealthExtraFile"] = "存在额外文件",
        ["ModHealthUnmanagedExternal"] = "未接管的外部模组",
        ["ModHealthIndeterminate"] = "完整性未知",
        ["UnusedDependencies"] = "无用前置",
        ["UnusedDependencyCountFormat"] = "发现 {0} 个可检查清理的无用前置。",
        ["Installed"] = "已安装",
        ["Disabled"] = "已停用",
        ["NoMods"] = "没有受管理的 Mod",
        ["NoSnapshots"] = "没有快照",
        ["CreateSnapshot"] = "创建快照",
        ["Restore"] = "恢复",
        ["StatusChecking"] = "正在检查实例...",
        ["StatusReady"] = "就绪",
        ["ErrorDirectoryNotFound"] = "目录不存在",
        ["ErrorFileNotFound"] = "文件不存在",
        ["ErrorFileLocked"] = "文件正被其他进程占用",
        ["ErrorAccessDenied"] = "拒绝访问",
        ["ErrorNetworkRequestFailed"] = "网络请求失败",
        ["ErrorNetworkTimeout"] = "网络请求超时",
        ["ErrorDataInvalid"] = "数据无效或格式损坏",
        ["ErrorVerificationFailed"] = "文件校验失败",
        ["OperationFailed"] = "操作失败"
        ,["OperationComplete"] = "操作完成"
        ,["SelectLoader"] = "请先选择 Loader。"
        ,["SelectMod"] = "请先选择 Mod。"
        ,["SelectSnapshot"] = "请先选择快照。"
        ,["SelectSpeedrunTemplate"] = "请先选择速通模板。"
        ,["SnapshotNameRequired"] = "请输入快照名称。"
        ,["LoaderConflict"] = "存在冲突的 Loader 文件，需要手动修复。"
        ,["RepairBeforeSwitch"] = "切换前请先修复当前 Loader。"
        ,["LoaderSwitchBlockedByMods"] = "切换 Loader 前请先卸载全部受管 Mod（包括已停用和本地 Mod）；当前 Loader 与 Mod 文件均未更改。"
        ,["LoaderUninstallBlockedByMods"] = "卸载 Loader 前请先卸载全部受管 Mod（包括已停用和本地 Mod）；当前 Loader 与 Mod 文件均未更改。"
        ,["LoaderRepairPackageUnavailable"] = "当前目录中没有已安装 Loader 对应的安装包，无法自动修复。"
        ,["LoaderRepairIdentityUnknown"] = "Loader 收据缺失，且无法从已安装 Mod 中确定精确 Loader，无法自动恢复。"
        ,["LoaderReceiptRecoveryAvailable"] = "Loader 收据缺失，但可从已安装的受管 Mod 确定原 Loader；点击修复即可恢复。"
        ,["ExternalLoaderBlocked"] = "检测到未由 Crystalfly 管理的 Loader。为了保护原始游戏文件，无法直接覆盖或修复；请先下载或创建干净实例，再安装 Loader。"
        ,["LoaderRequired"] = "请先安装所需 Loader。"
        ,["WrongLoader"] = "此 Mod 需要其他 Loader"
        ,["UpdateRequired"] = "重新安装前需要先更新"
        ,["CloseGameFirst"] = "修改实例前请关闭所有空洞骑士进程。"
        ,["NoVanillaSource"] = "没有与此模板匹配的纯净原版实例。"
        ,["SpeedrunNeedsVerification"] = "专用副本已创建，正式开跑前请执行验证。"
        ,["SpeedrunUnverified"] = "专用副本已创建，但目录缺少可信文件清单，因此标记为未验证。"
        ,["InstallOrSwitch"] = "安装或切换"
        ,["Repair"] = "修复"
        ,["Uninstall"] = "卸载"
        ,["EnableDisable"] = "启用 / 停用"
        ,["Install"] = "安装"
        ,["AvailableMods"] = "可用 Mods"
        ,["InstalledMods"] = "已安装 Mod"
        ,["ModPresets"] = "整合包"
        ,["ModPresetsHint"] = "记录当前已启用 Mod 组合，再以追加或精确模式将整合包应用到此实例。"
        ,["ModPacks"] = "整合包"
        ,["ModPacksHint"] = "集中创建、导入、分享与应用 Mod 组合，需要时再展开清单。"
        ,["LocalModPacks"] = "本地整合包"
        ,["SearchModPacks"] = "搜索整合包"
        ,["CreateModPack"] = "新建整合包"
        ,["CreateModPackHint"] = "记录当前实例已启用的 Mod，并选择以后应用整合包时采用的模式。"
        ,["CopyModPackHint"] = "请输入复制后的整合包名称。"
        ,["NoMatchingModPacks"] = "没有匹配的整合包。可以从当前实例新建，或导入 JSON。"
        ,["ModPackSummary"] = "兼容范围与应用摘要"
        ,["GameBuild"] = "游戏构建"
        ,["ModCount"] = "Mod 数量"
        ,["ViewModPackContents"] = "查看 Mod 清单"
        ,["SearchModPackContents"] = "搜索此 Mod 清单"
        ,["NoModPackSelected"] = "选择一个整合包"
        ,["NoModPackSelectedHint"] = "在左侧选择整合包，即可检查兼容范围并应用到当前实例。"
        ,["ImportSharedPresetHint"] = "输入 12 位分享码。导入后仍保存为本地整合包 JSON。"
        ,["PresetName"] = "整合包名称"
        ,["PresetMode"] = "应用模式"
        ,["PresetModeAppend"] = "追加"
        ,["PresetModeExact"] = "精确"
        ,["CreatePreset"] = "从当前 Mod 创建"
        ,["RecapturePreset"] = "重新捕获"
        ,["CopyPreset"] = "复制整合包"
        ,["DeletePreset"] = "删除整合包"
        ,["ImportPreset"] = "导入 JSON"
        ,["ExportPreset"] = "导出 JSON"
        ,["SharePreset"] = "分享整合包"
        ,["PresetShareCode"] = "12 位分享码"
        ,["ImportSharedPreset"] = "导入分享码"
        ,["ApplyPreset"] = "应用整合包"
        ,["RestorePresetState"] = "恢复应用前状态"
        ,["PresetEntries"] = "整合包条目"
        ,["NoPresetsAction"] = "尚无整合包。可以从当前已启用的 Mod 新建。"
        ,["PresetNameRequired"] = "请输入整合包名称。"
        ,["PresetNoChanges"] = "此整合包没有可自动执行的更改。"
        ,["PresetExported"] = "整合包已导出。"
        ,["PresetShared"] = "整合包分享已创建。"
        ,["PresetShareLink"] = "分享链接"
        ,["PresetShareLinkCopied"] = "整合包分享链接已复制。"
        ,["PresetTargetInstance"] = "目标实例"
        ,["PresetJsonFiles"] = "JSON 文件"
        ,["PresetJsonFileRequired"] = "请选择 JSON 整合包文件。"
        ,["ConfirmDeletePresetTitle"] = "删除整合包？"
        ,["ConfirmDeletePresetMessage"] = "将删除本地整合包定义，不会改动已安装 Mod。"
        ,["ConfirmApplyPresetTitle"] = "应用整合包？"
        ,["ConfirmApplyPresetMessage"] = "请检查安装项、启停变更、将停用的 Mod 和未解决的本地条目，确认后加入下载队列。"
        ,["PresetStepInstall"] = "安装"
        ,["PresetStepEnable"] = "启用"
        ,["PresetStepDisable"] = "停用"
        ,["PresetStepUnresolved"] = "未解决"
        ,["PresetStepBlocked"] = "已阻止"
        ,["PresetStateSatisfied"] = "已就绪"
        ,["PresetStatePending"] = "将更改"
        ,["PresetStateUnresolved"] = "需要本地文件"
        ,["PresetStateBlocked"] = "已阻止"
        ,["SnapshotName"] = "快照名称"
        ,["Template"] = "模板"
        ,["EnvironmentName"] = "环境名称"
        ,["LocalModPath"] = "本地 ZIP 或 DLL 路径"
        ,["ImportLocalMod"] = "导入本地 Mod"
        ,["LocalModPathRequired"] = "请选择存在的本地 ZIP 或 DLL。"
        ,["LocalModType"] = "仅支持导入 ZIP 与 DLL。"
        ,["Cancel"] = "取消"
        ,["Save"] = "保存"
        ,["CustomCatalogSources"] = "自定义目录源"
        ,["CustomModLinks"] = "自定义 ModLinks"
        ,["CustomModLinksHint"] = "可选的 HK ModLinks 完整替换源，必须绑定一个精确游戏版本与 Modding API Loader；自定义源始终未验证。清空网址可恢复官方源。"
        ,["CustomModLinksInvalid"] = "请输入 HTTPS 地址，并选择精确游戏版本与 Modding API Loader。"
        ,["CustomModLinksRemote"] = "自定义 ModLinks · 远程"
        ,["CustomModLinksCached"] = "自定义 ModLinks · 缓存"
        ,["CustomModLinksFailed"] = "自定义 ModLinks · 不可用"
        ,["UnverifiedSource"] = "未验证来源"
        ,["SelectVersionRootTitle"] = "选择空洞骑士版本根目录"
        ,["SelectModPackageTitle"] = "选择 Mod 安装包"
        ,["ModFileType"] = "空洞骑士 Mod"
        ,["Confirm"] = "继续"
        ,["ConfirmLoaderUninstallTitle"] = "卸载 Loader？"
        ,["ConfirmLoaderUninstallMessage"] = "将从所选实例移除受管理的 Loader 文件。"
        ,["ConfirmModUninstallTitle"] = "卸载 Mod？"
        ,["ConfirmModUninstallMessage"] = "将从此实例移除所选的受管理 Mod。"
        ,["ConfirmSnapshotRestoreTitle"] = "恢复快照？"
        ,["ConfirmSnapshotRestoreMessage"] = "当前实例的存档数据将被所选快照替换。"
        ,["DeleteSnapshot"] = "删除快照"
        ,["ConfirmSnapshotDeleteTitle"] = "删除快照？"
        ,["ConfirmSnapshotDeleteMessage"] = "所选存档快照将被永久删除。"
        ,["NoInstancesAction"] = "未找到实例。请在设置中选择版本根目录，或刷新后重试。"
        ,["NoLoadersAction"] = "没有兼容的 Loader。请检查所选版本后刷新。"
        ,["NoAvailableModsAction"] = "没有兼容的 Mod。请在设置中检查目录源。"
        ,["NoInstalledModsAction"] = "此实例尚未安装受管理的 Mod。"
        ,["NoSnapshotsAction"] = "尚无快照。请在上方输入名称并创建第一个快照。"
        ,["NoSpeedrunTemplatesAction"] = "没有可用模板。请在设置中检查目录源。"
        ,["NoDownloadBuildsAction"] = "没有可用版本。请在设置中检查目录源。"
        ,["SearchGameVersions"] = "搜索版本号或 Manifest ID"
        ,["OtherHistoricalVersion"] = "其他历史版本"
        ,["HistoricalManifestTitle"] = "下载历史版本"
        ,["HistoricalManifestHint"] = "输入《空洞骑士》Windows Depot Manifest ID。"
        ,["HistoricalManifestId"] = "Manifest ID"
        ,["HistoricalInstanceName"] = "实例名称"
        ,["HistoricalManifestKnown"] = "已验证目录版本：{0}"
        ,["HistoricalManifestUnverified"] = "未验证历史版本 · 仅限原版"
        ,["InvalidHistoricalManifest"] = "请输入非零无符号 Manifest ID。"
        ,["UnverifiedHistoricalBuild"] = "未验证历史版本"
        ,["SteamLoginRequired"] = "请先登录 Steam，再加入下载队列。"
        ,["OpenSettings"] = "打开设置"
        ,["SelectInstance"] = "选择实例"
        ,["InstanceSettings"] = "实例设置"
        ,["Back"] = "返回"
        ,["CloneInstance"] = "克隆实例"
        ,["CloneInstanceName"] = "新实例名称"
        ,["CopySuffix"] = "副本"
        ,["FavoriteInstance"] = "收藏实例"
        ,["UnfavoriteInstance"] = "取消收藏"
        ,["InstanceShortcuts"] = "快捷方式"
        ,["InstanceFolder"] = "实例文件夹"
        ,["SaveFolder"] = "存档文件夹"
        ,["ModFolder"] = "Mod 文件夹"
        ,["InstanceActions"] = "实例操作"
        ,["RenameInstance"] = "修改实例名"
        ,["RenameInstanceHint"] = "修改名称时会同时重命名实例文件夹。"
        ,["RenameBlockedDownloads"] = "请先取消或完成此实例的下载任务，再修改实例名。"
        ,["RenameBlockedTransactions"] = "请先处理未完成的文件事务，再修改实例名。"
        ,["CompleteInstanceFiles"] = "补全文件"
        ,["CompleteInstanceFilesHint"] = "按当前版本的 Steam Manifest 补回缺失文件和损坏的核心文件；额外文件、Loader、Mod 与存档都会保留。"
        ,["DeleteInstance"] = "删除实例"
        ,["DeleteInstanceTitle"] = "永久删除实例"
        ,["DeleteInstanceMessage"] = "游戏目录、Loader、Mod、隔离存档和存档快照将被永久删除。"
        ,["PermanentDeleteWarning"] = "此操作会永久删除实例，且无法撤销。"
        ,["DeleteBlockedGameRunning"] = "请先关闭《空洞骑士》，再删除此实例。"
        ,["DeleteBlockedDownloads"] = "请先取消或完成此实例的下载任务，再删除实例。"
        ,["DeleteBlockedTransactions"] = "请先处理未完成的文件事务，再删除此实例。"
        ,["DeleteCleanupPending"] = "实例已删除，残留文件将在下次启动时继续清理。"
        ,["DeleteRecoveryNeedsAttention"] = "存在需要处理的实例删除事务。"
        ,["CloneNameRequired"] = "请输入克隆实例名称。"
        ,["CloneVanillaOnly"] = "请选择原版实例克隆，确保 Loader 与 Mod 状态相互独立。"
        ,["LoadNormaliserSeconds"] = "加载标准化秒数"
        ,["SpeedrunTemplateMissing"] = "速通模板已不可用。"
        ,["SpeedrunBuildMissing"] = "速通对应的游戏版本已不可用。"
        ,["SpeedrunManifestMissing"] = "速通文件清单已不可用。"
        ,["SpeedrunVerified"] = "正式速通环境启动前完整性检查通过。"
        ,["SpeedrunVerifiedWithWarnings"] = "技术校验通过；开始前请确认当前分类的规则警告。"
        ,["SpeedrunVerificationFailed"] = "正式速通环境启动前完整性检查失败，已阻止启动。"
        ,["SpeedrunUnverifiedReport"] = "已生成未验证速通报告。"
        ,["SpeedrunOpenReport"] = "打开报告"
        ,["SpeedrunCopyReportPath"] = "复制报告路径"
        ,["SpeedrunReportPathCopied"] = "报告路径已复制。"
        ,["SpeedrunReportPathMissing"] = "速通报告已不存在。"
        ,["RecoveryNeedsAttention"] = "文件事务需要手动处理，处理前禁止启动。"
        ,["AdvancedLocalLoader"] = "高级本地 Loader 导入"
        ,["LocalLoaderManifestPath"] = "Crystalfly Loader 清单（.json）"
        ,["LocalLoaderManifestRequired"] = "请选择存在的 Crystalfly Loader 清单。"
        ,["SelectLoaderManifestTitle"] = "选择 Crystalfly Loader 清单"
        ,["LoaderManifestFileType"] = "Crystalfly Loader 清单"
        ,["ImportLocalLoader"] = "导入本地 Loader"
        ,["Unverified"] = "未验证"
        ,["UnverifiedLocalLoader"] = "本地 Loader · 未验证"
        ,["VerifiedCatalogLoader"] = "目录 Loader · 安装包已验证"
        ,["FilterMods"] = "搜索 Mods"
        ,["FilterAll"] = "全部状态"
        ,["Enabled"] = "已启用"
        ,["Updates"] = "可更新"
        ,["Update"] = "更新"
        ,["UpdateAvailable"] = "有可用更新"
        ,["SelectedMods"] = "个 Mod 已选择"
        ,["Information"] = "信息"
        ,["OpenFolder"] = "打开目录"
        ,["SelectMultiple"] = "多选"
        ,["SelectAll"] = "全选"
        ,["ClearSelection"] = "取消选择"
        ,["BatchActions"] = "批量操作"
        ,["BatchEnable"] = "启用所选"
        ,["BatchDisable"] = "停用所选"
        ,["BatchUninstall"] = "卸载所选"
        ,["Enable"] = "启用"
        ,["Disable"] = "停用"
        ,["Missing"] = "缺失"
        ,["NeedsRepair"] = "需要修复"
        ,["DependencyProblem"] = "依赖异常"
        ,["NeedsAttention"] = "需要处理"
        ,["LaunchBlocked"] = "启动前检查未通过，解决问题后才能启动。"
        ,["NoUpdateAvailable"] = "所选 Mod 没有可用的目录更新。"
        ,["ReverseDependencies"] = "请先移除依赖这些 Mod 的项目，或将其一并选择"
        ,["RefreshFailed"] = "刷新失败"
        ,["GameFiles"] = "游戏文件"
        ,["LoaderStatus"] = "Loader 状态"
        ,["LogFiles"] = "日志文件"
        ,["NoLogs"] = "没有找到此实例支持的日志文件。"
        ,["RefreshLogs"] = "刷新日志"
        ,["ConfirmBulkUninstallTitle"] = "卸载所选 Mods？"
        ,["ConfirmBulkUninstallMessage"] = "将从此实例移除所选的受管理 Mods。"
        ,["CannotUninstallDependents"] = "以下已安装 Mods 依赖当前选择："
        ,["DependencyImpact"] = "依赖影响"
        ,["DependencyList"] = "列表"
        ,["DependencyGraph"] = "依赖图"
        ,["DependencyGraphFocus"] = "当前 Mod 关系"
        ,["DependencyGraphAll"] = "全部已安装 Mod"
        ,["DependencyRelationshipUnknown"] = "关系未知"
        ,["RepairDependencies"] = "修复依赖"
        ,["WillDelete"] = "将删除"
        ,["DependenciesWillBeMissing"] = "依赖将缺失"
        ,["WillReEnable"] = "将重新启用"
        ,["WillDownloadAndInstall"] = "将下载并安装"
        ,["CannotRepair"] = "无法修复"
        ,["Target"] = "目标"
        ,["Unresolved"] = "未解决"
        ,["GameVersions"] = "游戏版本"
        ,["ModMarket"] = "Mod 市场"
        ,["MarketTitle"] = "发现 Mod"
        ,["MarketHint"] = "浏览官方 HK ModLinks 目录，并将兼容版本安装到实例。"
        ,["MarketSearch"] = "搜索 Mod"
        ,["MarketBuild"] = "游戏版本"
        ,["MarketLoader"] = "Loader"
        ,["MarketSource"] = "来源"
        ,["MarketTag"] = "标签"
        ,["ActivityAll"] = "全部动态"
        ,["RecentlyAdded"] = "最近新增"
        ,["RecentlyUpdated"] = "最近更新"
        ,["MarketEmpty"] = "没有符合当前筛选条件的 Mod。"
        ,["ViewDetails"] = "查看详情"
        ,["BackToMarket"] = "返回 Mod 市场"
        ,["Authors"] = "作者"
        ,["Tags"] = "标签"
        ,["Integrations"] = "集成"
        ,["SupportedBuilds"] = "支持版本"
        ,["Dependencies"] = "依赖"
        ,["QueueDetails"] = "任务明细"
        ,["Source"] = "来源"
        ,["Repository"] = "仓库"
        ,["ModDetails"] = "模组详情"
        ,["CurrentVersion"] = "当前版本"
        ,["LatestVersion"] = "最新版本"
        ,["InstallHistory"] = "安装历史"
        ,["InstalledAt"] = "安装于"
        ,["ModifiedFiles"] = "被修改的文件"
        ,["FileConflicts"] = "文件冲突"
        ,["CheckAllForUpdates"] = "检查全部可更新"
        ,["UpdatesAvailable"] = "有可用更新"
        ,["ConflictWith"] = "与以下模组冲突"
        ,["ExpandNode"] = "展开节点"
        ,["CollapseNode"] = "收起节点"
        ,["Readme"] = "README"
        ,["LatestReleaseNotes"] = "最新发行说明"
        ,["ReinstallMod"] = "重装 Mod"
        ,["GlobalSettings"] = "全局设置"
        ,["DeleteGlobalSettings"] = "删除全局设置"
        ,["OpenLogs"] = "查看日志"
        ,["ContentRemote"] = "在线内容"
        ,["ContentCached"] = "缓存内容"
        ,["ContentUnavailable"] = "内容不可用"
        ,["OfficialEnglishDescription"] = "官方英文说明"
        ,["Issues"] = "问题反馈"
        ,["InstallModTitle"] = "安装 Mod"
        ,["InstallToInstance"] = "选择目标实例"
        ,["NoInstallTargets"] = "没有可用于安装此 Mod 的实例。"
        ,["InstallSelectedMod"] = "安装所选 Mod"
        ,["MarketWillInstallLoader"] = "将先安装 {0}"
        ,["MarketWrongLoaderBlocked"] = "已安装其他 Loader"
        ,["MarketDriftedBlocked"] = "Loader 文件已漂移，请先修复"
        ,["MarketIncompatibleBlocked"] = "此游戏版本与 Mod 或其依赖不兼容"
        ,["OfficialSpeedrunModBlocked"] = "正式速通实例禁止安装 Mod"
        ,["AboutSpeedrunSources"] = "速通资料来源"
        ,["AboutSpeedrunSourcesDescription"] = "RuntimePatches 参考 HK Speedrunning 与 HK-Resources。AssemblyPatches v1.0.2 的仓库源码不能完全复现其发布二进制，因此客户端以固定的 ZIP 与 DLL SHA-256 为准。"
        ,["ExternalLoader"] = "外部安装"
        ,["HKModLinks"] = "HK ModLinks"
        ,["HKModLinksHint"] = "官方 Mod 目录 · 只读"
        ,["CatalogRemote"] = "远程目录"
        ,["CatalogCached"] = "已缓存"
        ,["CatalogFailed"] = "加载失败"
        ,["DownloadQueue"] = "下载队列"
        ,["DownloadQueueHint"] = "下载会在后台继续；仅在游戏退出后修改目标实例文件。"
        ,["DownloadQueueEmpty"] = "暂无下载任务。请下载游戏版本，或从 Mod 市场安装 Mod。"
        ,["AddToDownloadQueue"] = "加入下载队列"
        ,["AddedToDownloadQueue"] = "已加入下载队列"
        ,["QueueTaskAlreadyExists"] = "下载队列中已存在此任务"
        ,["RequiredComponents"] = "所需组件"
        ,["MainMod"] = "主 Mod"
        ,["Dependency"] = "前置依赖"
        ,["WillInstall"] = "将安装"
        ,["WillUpdate"] = "将更新"
        ,["InstallationPlan"] = "安装计划"
        ,["ConfirmCloseDownloadsTitle"] = "仍有未完成下载，是否关闭？"
        ,["ConfirmCloseDownloadsMessage"] = "正在传输的任务会在安全边界停止；未完成和失败任务将保存，并可在下次启动后继续。"
        ,["QueueTarget"] = "目标实例"
        ,["QueueRetry"] = "重试"
        ,["QueueRetryCount"] = "已重试：{0}"
        ,["QueueRetryAll"] = "全部重试"
        ,["QueuePauseAll"] = "全部暂停"
        ,["QueueResumeAll"] = "全部恢复"
        ,["QueueClearCompleted"] = "清除已完成"
        ,["QueueCopyError"] = "复制错误"
        ,["QueueCompletedFormat"] = "{0} 下载完成"
        ,["DownloadErrorOffline"] = "离线"
        ,["DownloadErrorNetwork"] = "网络"
        ,["DownloadErrorVerification"] = "校验"
        ,["DownloadErrorPermission"] = "权限"
        ,["DownloadErrorOther"] = "其他"
        ,["QueueStatePending"] = "等待中"
        ,["QueueStateRunning"] = "执行中"
        ,["QueueStateTransferring"] = "正在下载"
        ,["QueueStateWaitingForGameExit"] = "等待游戏退出"
        ,["QueueStateWaitingForSteamLogin"] = "等待登录 Steam"
        ,["QueueStateInstalling"] = "正在安装"
        ,["QueueStateCompleted"] = "已完成"
        ,["QueueStateFailed"] = "失败"
        ,["QueueStateBlocked"] = "已阻塞"
        ,["QueueStateCanceled"] = "已取消"
        ,["QueueStageStarting"] = "正在开始"
        ,["QueueStageRetrying"] = "正在重试"
        ,["QueueStageCached"] = "使用已缓存安装包"
        ,["QueueStageSatisfied"] = "已安装"
        ,["CloseWithDownloadsTitle"] = "仍有下载任务，确定关闭？"
        ,["CloseWithDownloadsMessage"] = "活动下载会在安全边界取消，并在下次启动时恢复到队列。"
        ,["ActiveDownloads"] = "{0} 个活动下载"
        ,["ExternalCommandTitle"] = "确认外部命令"
        ,["ExternalCommandMessage"] = "其他程序或链接请求执行此操作。请先核对目标，再运行命令。"
        ,["RunCommand"] = "运行命令"
        ,["ProtocolDownloadMod"] = "下载并安装 Mod"
        ,["ProtocolReinstallAllMods"] = "重新安装全部可处理的受管理 Mod"
        ,["ProtocolResetApplicationSettings"] = "重置 Crystalfly 设置"
        ,["ProtocolUseOfficialModLinks"] = "切换到官方 HK ModLinks"
        ,["ProtocolUseCustomModLinks"] = "切换到自定义 ModLinks 源"
        ,["ProtocolDeleteModSettings"] = "删除一个 Mod 的全局设置"
        ,["ProtocolDeleteAllModSettings"] = "删除全部官方 Mod 的全局设置"
        ,["ProtocolLaunchInstance"] = "通过普通启动预检启动实例"
        ,["ProtocolOpenModLocation"] = "打开已安装 Mod 的目录"
        ,["ProtocolImportPresetShare"] = "将分享的整合包导入当前实例"
        ,["ProtocolNoModsToReinstall"] = "没有可重新安装的受管理 Mod。"
        ,["ProtocolSettingsReset"] = "Crystalfly 设置已重置，请重新选择版本根目录。"
        ,["ProtocolNoGlobalSettings"] = "没有找到匹配的全局设置文件。"
        ,["ProtocolOpenFolderFailed"] = "Windows 没有打开 Mod 目录。"
        ,["InvalidExternalCommand"] = "外部命令已被拒绝"
        ,["ExternalCommandBusy"] = "请等待当前 Crystalfly 操作完成，再执行外部命令。"
        ,["ExternalCommandGameRunning"] = "请先关闭《空洞骑士》，再执行外部命令。"
        ,["ExternalCommandDownloadsActive"] = "请先完成或取消下载任务，再修改应用源或设置。"
        ,["ExternalCommandClosing"] = "Crystalfly 正在关闭，外部命令未执行。"
        ,["ApplicationUpdates"] = "应用更新"
        ,["ApplicationUpdatesHint"] = "每天检查一次签名稳定通道；下载沿用当前 GitHub 线路。"
        ,["CheckForUpdates"] = "自动检查更新"
        ,["CheckNow"] = "立即检查"
        ,["CurrentVersionFormat"] = "当前版本：{0}"
        ,["UpdateChecksDisabled"] = "已关闭自动更新检查"
        ,["UpdateCheckNotDue"] = "最近 24 小时内已检查"
        ,["ApplicationUpToDate"] = "Crystalfly 已是最新版本"
        ,["UpdateVersionSkipped"] = "已跳过此版本"
        ,["ApplicationUpdateAvailableFormat"] = "发现新版本 {0}"
        ,["UpdateCheckFailed"] = "更新检查失败"
        ,["UpdateManifestUnavailable"] = "最新版本尚未发布签名更新清单"
        ,["DownloadingApplicationUpdate"] = "正在下载并验证更新……"
        ,["ApplicationUpdateStarting"] = "正在启动更新程序……"
        ,["ApplicationUpdateTitle"] = "Crystalfly 有可用更新"
        ,["ApplicationUpdateVersionFormat"] = "版本 {0}"
        ,["UpdateNow"] = "立即更新"
        ,["Later"] = "稍后"
        ,["SkipThisVersion"] = "跳过此版本"
        ,["ProtocolRegistration"] = "crystalfly:// 协议"
        ,["ProtocolRegistrationHint"] = "安装包会注册整合包分享和外部命令所用的链接协议。"
        ,["ProtocolRegistered"] = "已注册"
        ,["ProtocolNotRegistered"] = "未注册"
        ,["LatestBuild"] = "最新版"
        ,["GameDirectories"] = "游戏目录"
        ,["GameDirectoriesHint"] = "先选择根目录，再选择其中的空洞骑士实例。"
        ,["AddGameDirectory"] = "添加目录"
        ,["RemoveGameDirectory"] = "移除目录"
        ,["RefreshGameDirectories"] = "刷新目录"
        ,["ScanGameDirectories"] = "扫描游戏目录"
        ,["ScanGameDirectoriesProgress"] = "正在扫描…… 已检查 {0} 个目录"
        ,["NoGameDirectories"] = "尚未登记游戏目录。"
        ,["NoGameDirectoryCandidates"] = "该目录中没有发现空洞骑士安装。"
        ,["SelectGameDirectory"] = "选择游戏目录"
        ,["GameDirectoryDiscoveryTitle"] = "查找空洞骑士安装"
        ,["GameDirectoryDiscoveryHint"] = "扫描 Steam 库或添加文件夹；确认前不会登记任何目录。"
        ,["ConfirmAddDirectories"] = "添加所选目录"
        ,["SkipForNow"] = "暂时跳过"
        ,["ScanPending"] = "等待扫描"
        ,["Scanning"] = "正在扫描"
        ,["ScanReady"] = "已就绪"
        ,["ScanFailed"] = "不可用"
        ,["InvalidGameDirectory"] = "游戏目录没有有效的父文件夹。"
        ,["SteamDirectoryRiskTitle"] = "管理 Steam 原始安装？"
        ,["SteamDirectoryRiskHint"] = "原地管理可能与 Steam 更新或文件验证冲突，推荐迁移实例。"
        ,["MigrateInstance"] = "迁移实例"
        ,["AcceptSteamRisk"] = "无视风险并原地接管"
        ,["SelectMigrationTarget"] = "选择非 Steam 目标目录"
        ,["MigrationTargetMustNotBeSteam"] = "迁移目标必须是非 Steam 游戏目录。"
        ,["MigrationBlockedByDownload"] = "请先完成或取消该实例的下载任务，再进行迁移。"
        ,["DeleteSteamInstanceTitle"] = "移除 Steam 安装？"
        ,["DeleteSteamInstanceHint"] = "可以仅从 Crystalfly 移除，或永久删除游戏目录。"
        ,["PermanentlyDeleteDirectory"] = "永久删除目录"
        ,["UnregisterOnly"] = "仅从 Crystalfly 移除"
    };

    private IReadOnlyDictionary<string, string> values = Chinese;

    public string this[string key] => values.TryGetValue(key, out var value) ? value : key;

    public CultureInfo Culture { get; private set; } = CultureInfo.GetCultureInfo("zh-CN");

    public void Apply(UiLanguage language)
    {
        var useChinese = language == UiLanguage.SimplifiedChinese
            || (language == UiLanguage.FollowSystem
                && CultureInfo.CurrentUICulture.Name.StartsWith("zh", StringComparison.OrdinalIgnoreCase));
        Culture = CultureInfo.GetCultureInfo(useChinese ? "zh-CN" : "en-US");
        values = useChinese ? Chinese : English;
        // Avalonia registers indexer binding paths (Loc[key]) under the CLR indexer
        // property name "Item"; WPF-style "Item[]" notifications are ignored by its
        // INPC accessor, so indexer bindings never refreshed after a language switch.
        OnPropertyChanged(IndexerChangedNotification);
    }

    private const string IndexerChangedNotification = "Item";

    // Test-only hook: lets binding tests exercise the exact Avalonia INPC contract for
    // indexer refreshes without constructing a second language dictionary.
    internal void RaiseTestNotification(string? propertyName) => OnPropertyChanged(propertyName);

    /// <summary>
    /// Formats an exception for user-visible display. Exceptions whose meaning is
    /// recognizable (directory/file missing, access denied, network failure, ...) are
    /// mapped to a localized message; everything else falls back to the generic
    /// "Operation failed" wording with the original (English) exception message as detail.
    /// </summary>
    public string ErrorMessageFor(Exception exception)
    {
        var key = LocalizedErrorKey(exception);
        return key is not null && values.TryGetValue(key, out var localized)
            ? localized
            : $"{values["OperationFailed"]}: {exception.Message}";
    }

    private static string? LocalizedErrorKey(Exception exception)
    {
        if (exception is DirectoryNotFoundException)
        {
            return "ErrorDirectoryNotFound";
        }
        if (exception is FileNotFoundException)
        {
            return "ErrorFileNotFound";
        }
        if (exception is UnauthorizedAccessException)
        {
            return "ErrorAccessDenied";
        }
        if (exception is HttpRequestException)
        {
            return "ErrorNetworkRequestFailed";
        }
        if (exception is TimeoutException)
        {
            return "ErrorNetworkTimeout";
        }
        if (exception is InvalidDataException or System.Text.Json.JsonException)
        {
            return "ErrorDataInvalid";
        }
        if (exception is System.Security.Cryptography.CryptographicException)
        {
            return "ErrorVerificationFailed";
        }
        if (exception is IOException ioException && IsFileLocked(ioException))
        {
            return "ErrorFileLocked";
        }
        return null;
    }

    private static bool IsFileLocked(IOException exception) =>
        exception.HResult is unchecked((int)0x80070020) or unchecked((int)0x80070021) // ERROR_SHARING_VIOLATION / ERROR_LOCK_VIOLATION
        || exception.Message.Contains("being used by another process", StringComparison.OrdinalIgnoreCase);
}
