using System.Globalization;
using Crystalfly.Core.Configuration;

namespace Crystalfly.App.ViewModels;

public sealed class LocalizationViewModel : ViewModelBase
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["NavLaunch"] = "Launch",
        ["NavVersions"] = "Instances",
        ["NavManage"] = "Manage",
        ["NavSpeedrun"] = "Speedrun",
        ["NavDownloads"] = "Downloads",
        ["NavSettings"] = "Settings",
        ["WindowMinimize"] = "Minimize",
        ["WindowMaximize"] = "Maximize / restore",
        ["WindowClose"] = "Close",
        ["Ready"] = "Ready",
        ["ReadyHint"] = "The selected instance passed launch checks.",
        ["NoInstance"] = "No instance selected",
        ["ChooseRoot"] = "Choose a version root to discover Hollow Knight instances.",
        ["LaunchGame"] = "Launch game",
        ["LaunchIssues"] = "Launch issues",
        ["LaunchIssueCountFormat"] = "{0} launch issues",
        ["LaunchWarningTitle"] = "Review launch issues",
        ["LaunchWarningMessage"] = "Mod integrity or dependency issues were found. Review them before continuing.",
        ["LaunchBlockedTitle"] = "Launch blocked",
        ["ForceLaunch"] = "Force launch",
        ["DoNotRemindLaunchWarnings"] = "Do not remind me again while these exact issues stay unchanged",
        ["LaunchIssueExecutableMissing"] = "The game executable is missing",
        ["LaunchIssueGameAlreadyRunning"] = "Hollow Knight is already running",
        ["LaunchIssueUnknownBuild"] = "The build and Loader combination is unsupported",
        ["LaunchIssueLoaderConflict"] = "Conflicting Loader files were detected",
        ["LaunchIssueLoaderDrifted"] = "Loader files have drifted",
        ["LaunchIssueMissingDependency"] = "A required Mod dependency is missing",
        ["LaunchIssueDisabledDependency"] = "A required Mod dependency is disabled",
        ["LaunchIssueTransactionNeedsAttention"] = "A file transaction needs attention",
        ["LaunchIssueLocalLowNotReady"] = "The isolated save directory is not ready",
        ["LaunchIssueModCriticalFileMissing"] = "A required Mod file is missing",
        ["LaunchIssueModModifiedFile"] = "A Mod file was modified",
        ["LaunchIssueModExtraFile"] = "A Mod contains an extra file",
        ["LaunchIssueExternalMod"] = "An unmanaged external Mod was found",
        ["LaunchIssueModIndeterminate"] = "Mod integrity could not be determined",
        ["Refresh"] = "Refresh",
        ["ManageInstance"] = "Instance settings",
        ["LoaderFiles"] = "Game and loader files",
        ["ModDependencies"] = "Mod dependencies",
        ["SaveIsolation"] = "Save isolation",
        ["Complete"] = "Complete",
        ["NoConflicts"] = "No conflicts",
        ["Mounted"] = "Ready",
        ["Instances"] = "Instances",
        ["InstancesHint"] = "Known versions and full-copy environments under the selected root.",
        ["SearchInstances"] = "Search instances",
        ["Overview"] = "Overview",
        ["Loader"] = "Loader",
        ["Mods"] = "Mods",
        ["Snapshots"] = "Save Snapshots",
        ["Logs"] = "Logs",
        ["SpeedrunTitle"] = "Official speedrun environments",
        ["SpeedrunHint"] = "Create a dedicated verified copy. Daily instances are never modified.",
        ["CreateEnvironment"] = "Create environment",
        ["DownloadsTitle"] = "Downloads",
        ["DownloadsHint"] = "Steam public builds and cached packages.",
        ["SteamAccount"] = "Steam account",
        ["SignInQr"] = "Sign in with QR",
        ["SignOut"] = "Sign out",
        ["SettingsTitle"] = "Settings",
        ["VersionRoot"] = "Version root",
        ["Browse"] = "Browse",
        ["Language"] = "Language",
        ["Theme"] = "Theme",
        ["GitHubRoute"] = "Download route",
        ["GitHubRouteHint"] = "Choose how GitHub-hosted catalogs and packages are fetched.",
        ["OfflineMode"] = "Offline mode",
        ["OfflineModeHint"] = "Use only local data and verified caches. Network downloads wait until offline mode is disabled.",
        ["GitHubDirect"] = "GitHub direct",
        ["GitHubMirror"] = "GitHub mirror",
        ["TestLatency"] = "Test latency",
        ["LatencyTesting"] = "Testing...",
        ["LatencyTimeout"] = "Timeout",
        ["LatencyUnavailable"] = "Unavailable",
        ["LatencyCanceled"] = "Canceled",
        ["System"] = "System",
        ["Light"] = "Light",
        ["Dark"] = "Dark",
        ["FollowSystem"] = "Follow system",
        ["SimplifiedChinese"] = "Simplified Chinese",
        ["English"] = "English",
        ["Vanilla"] = "Vanilla",
        ["UnknownBuild"] = "Unknown build · vanilla only",
        ["Local"] = "Local",
        ["External"] = "External",
        ["Pinned"] = "Pinned",
        ["NeedsAttentionFilter"] = "Needs attention",
        ["PinMod"] = "Pin Mod",
        ["UnpinMod"] = "Unpin Mod",
        ["TakeOverMod"] = "Take over external Mod",
        ["RepairMod"] = "Repair Mod",
        ["AcceptCurrentFiles"] = "Accept current files",
        ["ReimportLocalMod"] = "Re-import local Mod",
        ["ExternalModReadOnly"] = "External Mods are read-only until they are taken over.",
        ["UnpinBeforeUninstall"] = "Unpin this Mod before uninstalling it.",
        ["ModHealthHealthy"] = "Healthy",
        ["ModHealthCriticalFileMissing"] = "Critical file missing",
        ["ModHealthModifiedFile"] = "Modified file",
        ["ModHealthExtraFile"] = "Extra file",
        ["ModHealthUnmanagedExternal"] = "Unmanaged external",
        ["ModHealthIndeterminate"] = "Integrity unknown",
        ["UnusedDependencies"] = "Unused dependencies",
        ["UnusedDependencyCountFormat"] = "{0} unused dependencies can be reviewed for cleanup.",
        ["Installed"] = "Installed",
        ["Disabled"] = "Disabled",
        ["NoMods"] = "No managed mods",
        ["NoSnapshots"] = "No snapshots",
        ["CreateSnapshot"] = "Create snapshot",
        ["Restore"] = "Restore",
        ["StatusChecking"] = "Checking instances...",
        ["StatusReady"] = "Ready",
        ["OperationFailed"] = "Operation failed"
        ,["OperationComplete"] = "Operation completed"
        ,["SelectLoader"] = "Select a loader first."
        ,["SelectMod"] = "Select a mod first."
        ,["SelectSnapshot"] = "Select a snapshot first."
        ,["SelectSpeedrunTemplate"] = "Select a speedrun template first."
        ,["SnapshotNameRequired"] = "Enter a snapshot name."
        ,["LoaderConflict"] = "Conflicting loader files require manual repair."
        ,["RepairBeforeSwitch"] = "Repair the current loader before switching."
        ,["LoaderSwitchBlockedByMods"] = "Uninstall every managed mod, including disabled and local mods, before switching loaders. The current loader and mod files were left unchanged."
        ,["ExternalLoaderBlocked"] = "An unmanaged loader is present. To protect the original game files, Crystalfly will not overwrite or repair it. Download or create a clean instance before installing a loader."
        ,["LoaderRequired"] = "Install the required loader first."
        ,["WrongLoader"] = "This mod requires another loader"
        ,["UpdateRequired"] = "Update is required before reinstalling"
        ,["CloseGameFirst"] = "Close every Hollow Knight process before changing this instance."
        ,["NoVanillaSource"] = "No clean vanilla instance matches this template."
        ,["SpeedrunNeedsVerification"] = "Dedicated copy created. Run verification before an official attempt."
        ,["SpeedrunUnverified"] = "Dedicated copy created as unverified because the catalog has no trusted file manifest."
        ,["InstallOrSwitch"] = "Install or switch"
        ,["Repair"] = "Repair"
        ,["Uninstall"] = "Uninstall"
        ,["EnableDisable"] = "Enable / disable"
        ,["Install"] = "Install"
        ,["AvailableMods"] = "Available mods"
        ,["InstalledMods"] = "Installed Mods"
        ,["SnapshotName"] = "Snapshot name"
        ,["Template"] = "Template"
        ,["EnvironmentName"] = "Environment name"
        ,["LocalModPath"] = "Local ZIP or DLL path"
        ,["ImportLocalMod"] = "Import local mod"
        ,["LocalModPathRequired"] = "Choose an existing local ZIP or DLL."
        ,["LocalModType"] = "Only ZIP and DLL mod imports are supported."
        ,["Cancel"] = "Cancel"
        ,["Save"] = "Save"
        ,["CustomCatalogSources"] = "Custom catalog sources"
        ,["CustomModLinks"] = "Custom ModLinks"
        ,["CustomModLinksHint"] = "Optional full replacement for HK ModLinks. Bind it to one exact game build and Modding API Loader. Custom sources are unverified. Clear the URL to restore the official source."
        ,["CustomModLinksInvalid"] = "Enter an HTTPS URL and select an exact game build and Modding API Loader."
        ,["CustomModLinksRemote"] = "Custom ModLinks · remote"
        ,["CustomModLinksCached"] = "Custom ModLinks · cached"
        ,["CustomModLinksFailed"] = "Custom ModLinks · unavailable"
        ,["UnverifiedSource"] = "Unverified source"
        ,["SelectVersionRootTitle"] = "Select Hollow Knight version root"
        ,["SelectModPackageTitle"] = "Select a mod package"
        ,["ModFileType"] = "Hollow Knight mod"
        ,["Confirm"] = "Continue"
        ,["ConfirmLoaderUninstallTitle"] = "Uninstall loader?"
        ,["ConfirmLoaderUninstallMessage"] = "Managed loader files will be removed from the selected instance."
        ,["ConfirmModUninstallTitle"] = "Uninstall mod?"
        ,["ConfirmModUninstallMessage"] = "The selected managed mod will be removed from this instance."
        ,["ConfirmSnapshotRestoreTitle"] = "Restore snapshot?"
        ,["ConfirmSnapshotRestoreMessage"] = "Current instance save data will be replaced with the selected snapshot."
        ,["NoInstancesAction"] = "No instances found. Choose a version root in Settings or refresh."
        ,["NoLoadersAction"] = "No compatible loaders. Refresh after checking the selected build."
        ,["NoAvailableModsAction"] = "No compatible mods. Check catalog sources in Settings."
        ,["NoInstalledModsAction"] = "No managed mods are installed in this instance."
        ,["NoSnapshotsAction"] = "No snapshots. Enter a name above to create the first one."
        ,["NoSpeedrunTemplatesAction"] = "No templates available. Check catalog sources in Settings."
        ,["NoDownloadBuildsAction"] = "No builds available. Check catalog sources in Settings."
        ,["OpenSettings"] = "Open settings"
        ,["SelectInstance"] = "Select instance"
        ,["InstanceSettings"] = "Instance settings"
        ,["Back"] = "Back"
        ,["CloneInstance"] = "Clone instance"
        ,["CloneInstanceName"] = "New instance name"
        ,["CopySuffix"] = "Copy"
        ,["DeleteInstance"] = "Delete instance"
        ,["DeleteInstanceTitle"] = "Permanently delete instance"
        ,["DeleteInstanceMessage"] = "The game directory, Loader, Mods, isolated saves and snapshots will be permanently deleted."
        ,["PermanentDeleteWarning"] = "This action permanently deletes the instance and cannot be undone."
        ,["DeleteBlockedGameRunning"] = "Close Hollow Knight before deleting this instance."
        ,["DeleteBlockedDownloads"] = "Cancel or finish downloads for this instance before deleting it."
        ,["DeleteBlockedTransactions"] = "Resolve unfinished file transactions before deleting this instance."
        ,["DeleteCleanupPending"] = "Instance deleted. Pending files will be cleaned on next start."
        ,["DeleteRecoveryNeedsAttention"] = "An unfinished instance deletion needs attention."
        ,["CloneNameRequired"] = "Enter a name for the cloned instance."
        ,["CloneVanillaOnly"] = "Clone a vanilla instance so loader and mod state stay independent."
        ,["LoadNormaliserSeconds"] = "Load normaliser seconds"
        ,["SpeedrunTemplateMissing"] = "The speedrun template is no longer available."
        ,["SpeedrunBuildMissing"] = "The speedrun game build is no longer available."
        ,["SpeedrunManifestMissing"] = "The speedrun file manifest is no longer available."
        ,["SpeedrunVerified"] = "Official speedrun pre-launch integrity check passed."
        ,["SpeedrunVerificationFailed"] = "Official speedrun pre-launch integrity check failed; launch is blocked."
        ,["SpeedrunUnverifiedReport"] = "Unverified speedrun report generated."
        ,["RecoveryNeedsAttention"] = "A file transaction needs manual attention before launch."
        ,["AdvancedLocalLoader"] = "Advanced local loader import"
        ,["LocalLoaderManifestPath"] = "Crystalfly loader manifest (.json)"
        ,["LocalLoaderManifestRequired"] = "Choose an existing Crystalfly loader manifest."
        ,["SelectLoaderManifestTitle"] = "Select Crystalfly loader manifest"
        ,["LoaderManifestFileType"] = "Crystalfly loader manifest"
        ,["ImportLocalLoader"] = "Import local loader"
        ,["Unverified"] = "Unverified"
        ,["UnverifiedLocalLoader"] = "Local loader · unverified"
        ,["VerifiedCatalogLoader"] = "Catalog loader · verified package"
        ,["FilterMods"] = "Search mods"
        ,["FilterAll"] = "All statuses"
        ,["Enabled"] = "Enabled"
        ,["Updates"] = "Updates"
        ,["Update"] = "Update"
        ,["UpdateAvailable"] = "Update available"
        ,["SelectedMods"] = "mods selected"
        ,["Information"] = "Information"
        ,["OpenFolder"] = "Open folder"
        ,["SelectMultiple"] = "Select multiple"
        ,["SelectAll"] = "Select all"
        ,["ClearSelection"] = "Clear selection"
        ,["BatchActions"] = "Batch actions"
        ,["BatchEnable"] = "Enable selected"
        ,["BatchDisable"] = "Disable selected"
        ,["BatchUninstall"] = "Uninstall selected"
        ,["Enable"] = "Enable"
        ,["Disable"] = "Disable"
        ,["Missing"] = "Missing"
        ,["NeedsRepair"] = "Needs repair"
        ,["DependencyProblem"] = "Dependency problem"
        ,["NeedsAttention"] = "Needs attention"
        ,["LaunchBlocked"] = "Launch is blocked until the failed preflight checks are resolved."
        ,["NoUpdateAvailable"] = "No catalog update is available for the selected mod."
        ,["ReverseDependencies"] = "Dependent mods must be removed or included first"
        ,["RefreshFailed"] = "Refresh failed"
        ,["GameFiles"] = "Game files"
        ,["LoaderStatus"] = "Loader state"
        ,["LogFiles"] = "Log files"
        ,["NoLogs"] = "No supported log files were found for this instance."
        ,["RefreshLogs"] = "Refresh logs"
        ,["ConfirmBulkUninstallTitle"] = "Uninstall selected mods?"
        ,["ConfirmBulkUninstallMessage"] = "The selected managed mods will be removed from this instance."
        ,["CannotUninstallDependents"] = "These installed mods depend on the selection:"
        ,["DependencyImpact"] = "Dependency impact"
        ,["RepairDependencies"] = "Repair dependencies"
        ,["WillDelete"] = "Will delete"
        ,["DependenciesWillBeMissing"] = "Dependencies will be missing"
        ,["WillReEnable"] = "Will re-enable"
        ,["WillDownloadAndInstall"] = "Will download and install"
        ,["CannotRepair"] = "Cannot repair"
        ,["Target"] = "Target"
        ,["Unresolved"] = "Unresolved"
        ,["GameVersions"] = "Game versions"
        ,["ModMarket"] = "Mod Market"
        ,["MarketTitle"] = "Discover mods"
        ,["MarketHint"] = "Browse the official HK ModLinks catalog and install a compatible release into an instance."
        ,["MarketSearch"] = "Search mods"
        ,["MarketBuild"] = "Game build"
        ,["MarketLoader"] = "Loader"
        ,["MarketSource"] = "Source"
        ,["MarketTag"] = "Tag"
        ,["ActivityAll"] = "All activity"
        ,["RecentlyAdded"] = "Recently added"
        ,["RecentlyUpdated"] = "Recently updated"
        ,["MarketEmpty"] = "No mods match the current filters."
        ,["ViewDetails"] = "View details"
        ,["BackToMarket"] = "Back to Mod Market"
        ,["Authors"] = "Authors"
        ,["Tags"] = "Tags"
        ,["Integrations"] = "Integrations"
        ,["SupportedBuilds"] = "Supported builds"
        ,["Dependencies"] = "Dependencies"
        ,["QueueDetails"] = "Task details"
        ,["Source"] = "Source"
        ,["Repository"] = "Repository"
        ,["Readme"] = "README"
        ,["LatestReleaseNotes"] = "Latest release notes"
        ,["ReinstallMod"] = "Reinstall Mod"
        ,["GlobalSettings"] = "Global settings"
        ,["DeleteGlobalSettings"] = "Delete global settings"
        ,["OpenLogs"] = "Open logs"
        ,["ContentRemote"] = "Live content"
        ,["ContentCached"] = "Cached content"
        ,["ContentUnavailable"] = "Content unavailable"
        ,["OfficialEnglishDescription"] = "Official English description"
        ,["Issues"] = "Issues"
        ,["InstallModTitle"] = "Install mod"
        ,["InstallToInstance"] = "Choose target instance"
        ,["NoInstallTargets"] = "No instances are available for this mod."
        ,["InstallSelectedMod"] = "Install selected mod"
        ,["MarketWillInstallLoader"] = "Will install {0} first"
        ,["MarketWrongLoaderBlocked"] = "Another Loader is installed"
        ,["MarketDriftedBlocked"] = "Loader files have drifted and must be repaired first"
        ,["MarketIncompatibleBlocked"] = "This game build is not compatible with the Mod and its dependencies"
        ,["OfficialSpeedrunModBlocked"] = "Official speedrun instances cannot install Mods"
        ,["ExternalLoader"] = "External"
        ,["HKModLinks"] = "HK ModLinks"
        ,["HKModLinksHint"] = "Official mod catalog · read-only"
        ,["CatalogRemote"] = "Remote"
        ,["CatalogCached"] = "Cached"
        ,["CatalogFailed"] = "Failed"
        ,["DownloadQueue"] = "Download queue"
        ,["DownloadQueueHint"] = "Downloads continue in the background. Instance files are changed only after the game exits."
        ,["DownloadQueueEmpty"] = "No downloads yet. Choose a game version or install a mod from the market."
        ,["AddToDownloadQueue"] = "Add to download queue"
        ,["AddedToDownloadQueue"] = "Added to download queue"
        ,["QueueTaskAlreadyExists"] = "This task is already in the download queue"
        ,["RequiredComponents"] = "Required components"
        ,["MainMod"] = "Main mod"
        ,["Dependency"] = "Dependency"
        ,["WillInstall"] = "Will install"
        ,["WillUpdate"] = "Will update"
        ,["InstallationPlan"] = "Installation plan"
        ,["ConfirmCloseDownloadsTitle"] = "Close with unfinished downloads?"
        ,["ConfirmCloseDownloadsMessage"] = "Active transfers will stop at a safe boundary. Unfinished and failed tasks will be saved and can resume after restart."
        ,["QueueTarget"] = "Target"
        ,["QueueRetry"] = "Retry"
        ,["QueueRetryCount"] = "Retries: {0}"
        ,["QueueStatePending"] = "Pending"
        ,["QueueStateRunning"] = "Running"
        ,["QueueStateTransferring"] = "Downloading"
        ,["QueueStateWaitingForGameExit"] = "Waiting for game to exit"
        ,["QueueStateWaitingForSteamLogin"] = "Waiting for Steam sign-in"
        ,["QueueStateInstalling"] = "Installing"
        ,["QueueStateCompleted"] = "Completed"
        ,["QueueStateFailed"] = "Failed"
        ,["QueueStateBlocked"] = "Blocked"
        ,["QueueStateCanceled"] = "Canceled"
        ,["QueueStageStarting"] = "Starting"
        ,["QueueStageRetrying"] = "Retrying"
        ,["QueueStageCached"] = "Using cached package"
        ,["QueueStageSatisfied"] = "Already installed"
        ,["CloseWithDownloadsTitle"] = "Close while downloads are active?"
        ,["CloseWithDownloadsMessage"] = "Active downloads will be canceled at the next safe boundary and restored to the queue on the next launch."
        ,["ActiveDownloads"] = "{0} active downloads"
    };

    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["NavLaunch"] = "启动",
        ["NavVersions"] = "实例",
        ["NavManage"] = "管理",
        ["NavSpeedrun"] = "速通",
        ["NavDownloads"] = "下载",
        ["NavSettings"] = "设置",
        ["WindowMinimize"] = "最小化",
        ["WindowMaximize"] = "最大化 / 还原",
        ["WindowClose"] = "关闭",
        ["Ready"] = "准备就绪",
        ["ReadyHint"] = "当前实例已通过启动前检查。",
        ["NoInstance"] = "未选择实例",
        ["ChooseRoot"] = "请选择版本根目录以发现空洞骑士实例。",
        ["LaunchGame"] = "启动游戏",
        ["LaunchIssues"] = "启动问题",
        ["LaunchIssueCountFormat"] = "{0} 个启动问题",
        ["LaunchWarningTitle"] = "检查启动问题",
        ["LaunchWarningMessage"] = "检测到模组完整性或前置问题，请确认后再继续。",
        ["LaunchBlockedTitle"] = "启动已阻止",
        ["ForceLaunch"] = "强制启动",
        ["DoNotRemindLaunchWarnings"] = "这些问题及文件哈希不变时不再提醒",
        ["LaunchIssueExecutableMissing"] = "游戏主程序缺失",
        ["LaunchIssueGameAlreadyRunning"] = "空洞骑士已经在运行",
        ["LaunchIssueUnknownBuild"] = "游戏构建与 Loader 组合不受支持",
        ["LaunchIssueLoaderConflict"] = "检测到冲突的 Loader 文件",
        ["LaunchIssueLoaderDrifted"] = "Loader 文件已经漂移",
        ["LaunchIssueMissingDependency"] = "缺少必要的模组前置",
        ["LaunchIssueDisabledDependency"] = "必要的模组前置已停用",
        ["LaunchIssueTransactionNeedsAttention"] = "文件事务需要处理",
        ["LaunchIssueLocalLowNotReady"] = "实例隔离存档尚未就绪",
        ["LaunchIssueModCriticalFileMissing"] = "模组必要文件缺失",
        ["LaunchIssueModModifiedFile"] = "模组文件已被修改",
        ["LaunchIssueModExtraFile"] = "模组目录包含额外文件",
        ["LaunchIssueExternalMod"] = "发现未接管的外部模组",
        ["LaunchIssueModIndeterminate"] = "暂时不能判定模组完整性",
        ["Refresh"] = "刷新",
        ["ManageInstance"] = "实例设置",
        ["LoaderFiles"] = "游戏与 Loader 文件",
        ["ModDependencies"] = "Mod 依赖关系",
        ["SaveIsolation"] = "存档隔离",
        ["Complete"] = "完整",
        ["NoConflicts"] = "无冲突",
        ["Mounted"] = "已就绪",
        ["Instances"] = "实例",
        ["InstancesHint"] = "所选根目录中的已知版本与完整复制环境。",
        ["SearchInstances"] = "搜索实例",
        ["Overview"] = "概览",
        ["Loader"] = "Loader",
        ["Mods"] = "Mods",
        ["Snapshots"] = "存档快照",
        ["Logs"] = "日志",
        ["SpeedrunTitle"] = "正式速通环境",
        ["SpeedrunHint"] = "创建专用验证副本，不修改日常实例。",
        ["CreateEnvironment"] = "创建环境",
        ["DownloadsTitle"] = "下载",
        ["DownloadsHint"] = "Steam public 版本与已缓存安装包。",
        ["SteamAccount"] = "Steam 账号",
        ["SignInQr"] = "扫码登录",
        ["SignOut"] = "退出账号",
        ["SettingsTitle"] = "设置",
        ["VersionRoot"] = "版本根目录",
        ["Browse"] = "浏览",
        ["Language"] = "语言",
        ["Theme"] = "主题",
        ["GitHubRoute"] = "下载线路",
        ["GitHubRouteHint"] = "选择获取 GitHub 目录和安装包的线路。",
        ["OfflineMode"] = "离线模式",
        ["OfflineModeHint"] = "仅使用本地数据和已验证缓存；网络下载会等待关闭离线模式。",
        ["GitHubDirect"] = "GitHub 直连",
        ["GitHubMirror"] = "GitHub 镜像",
        ["TestLatency"] = "测试延迟",
        ["LatencyTesting"] = "测试中...",
        ["LatencyTimeout"] = "超时",
        ["LatencyUnavailable"] = "不可用",
        ["LatencyCanceled"] = "已取消",
        ["System"] = "系统",
        ["Light"] = "亮色",
        ["Dark"] = "暗色",
        ["FollowSystem"] = "跟随系统",
        ["SimplifiedChinese"] = "简体中文",
        ["English"] = "English",
        ["Vanilla"] = "原版",
        ["UnknownBuild"] = "未知版本 · 仅允许原版",
        ["Local"] = "本地",
        ["External"] = "外部",
        ["Pinned"] = "已固定",
        ["NeedsAttentionFilter"] = "需要处理",
        ["PinMod"] = "固定模组",
        ["UnpinMod"] = "取消固定",
        ["TakeOverMod"] = "接管外部模组",
        ["RepairMod"] = "修复模组",
        ["AcceptCurrentFiles"] = "接受当前文件",
        ["ReimportLocalMod"] = "重新导入本地模组",
        ["ExternalModReadOnly"] = "外部模组在接管前为只读状态。",
        ["UnpinBeforeUninstall"] = "请先取消固定，再卸载此模组。",
        ["ModHealthHealthy"] = "正常",
        ["ModHealthCriticalFileMissing"] = "关键文件缺失",
        ["ModHealthModifiedFile"] = "文件已修改",
        ["ModHealthExtraFile"] = "存在额外文件",
        ["ModHealthUnmanagedExternal"] = "未接管的外部模组",
        ["ModHealthIndeterminate"] = "完整性未知",
        ["UnusedDependencies"] = "无用前置",
        ["UnusedDependencyCountFormat"] = "发现 {0} 个可检查清理的无用前置。",
        ["Installed"] = "已安装",
        ["Disabled"] = "已停用",
        ["NoMods"] = "没有受管理的 Mod",
        ["NoSnapshots"] = "没有快照",
        ["CreateSnapshot"] = "创建快照",
        ["Restore"] = "恢复",
        ["StatusChecking"] = "正在检查实例...",
        ["StatusReady"] = "就绪",
        ["OperationFailed"] = "操作失败"
        ,["OperationComplete"] = "操作完成"
        ,["SelectLoader"] = "请先选择 Loader。"
        ,["SelectMod"] = "请先选择 Mod。"
        ,["SelectSnapshot"] = "请先选择快照。"
        ,["SelectSpeedrunTemplate"] = "请先选择速通模板。"
        ,["SnapshotNameRequired"] = "请输入快照名称。"
        ,["LoaderConflict"] = "存在冲突的 Loader 文件，需要手动修复。"
        ,["RepairBeforeSwitch"] = "切换前请先修复当前 Loader。"
        ,["LoaderSwitchBlockedByMods"] = "切换 Loader 前请先卸载全部受管 Mod（包括已停用和本地 Mod）；当前 Loader 与 Mod 文件均未更改。"
        ,["ExternalLoaderBlocked"] = "检测到未由 Crystalfly 管理的 Loader。为了保护原始游戏文件，无法直接覆盖或修复；请先下载或创建干净实例，再安装 Loader。"
        ,["LoaderRequired"] = "请先安装所需 Loader。"
        ,["WrongLoader"] = "此 Mod 需要其他 Loader"
        ,["UpdateRequired"] = "重新安装前需要先更新"
        ,["CloseGameFirst"] = "修改实例前请关闭所有空洞骑士进程。"
        ,["NoVanillaSource"] = "没有与此模板匹配的纯净原版实例。"
        ,["SpeedrunNeedsVerification"] = "专用副本已创建，正式开跑前请执行验证。"
        ,["SpeedrunUnverified"] = "专用副本已创建，但目录缺少可信文件清单，因此标记为未验证。"
        ,["InstallOrSwitch"] = "安装或切换"
        ,["Repair"] = "修复"
        ,["Uninstall"] = "卸载"
        ,["EnableDisable"] = "启用 / 停用"
        ,["Install"] = "安装"
        ,["AvailableMods"] = "可用 Mods"
        ,["InstalledMods"] = "已安装 Mod"
        ,["SnapshotName"] = "快照名称"
        ,["Template"] = "模板"
        ,["EnvironmentName"] = "环境名称"
        ,["LocalModPath"] = "本地 ZIP 或 DLL 路径"
        ,["ImportLocalMod"] = "导入本地 Mod"
        ,["LocalModPathRequired"] = "请选择存在的本地 ZIP 或 DLL。"
        ,["LocalModType"] = "仅支持导入 ZIP 与 DLL。"
        ,["Cancel"] = "取消"
        ,["Save"] = "保存"
        ,["CustomCatalogSources"] = "自定义目录源"
        ,["CustomModLinks"] = "自定义 ModLinks"
        ,["CustomModLinksHint"] = "可选的 HK ModLinks 完整替换源，必须绑定一个精确游戏版本与 Modding API Loader；自定义源始终未验证。清空网址可恢复官方源。"
        ,["CustomModLinksInvalid"] = "请输入 HTTPS 地址，并选择精确游戏版本与 Modding API Loader。"
        ,["CustomModLinksRemote"] = "自定义 ModLinks · 远程"
        ,["CustomModLinksCached"] = "自定义 ModLinks · 缓存"
        ,["CustomModLinksFailed"] = "自定义 ModLinks · 不可用"
        ,["UnverifiedSource"] = "未验证来源"
        ,["SelectVersionRootTitle"] = "选择空洞骑士版本根目录"
        ,["SelectModPackageTitle"] = "选择 Mod 安装包"
        ,["ModFileType"] = "空洞骑士 Mod"
        ,["Confirm"] = "继续"
        ,["ConfirmLoaderUninstallTitle"] = "卸载 Loader？"
        ,["ConfirmLoaderUninstallMessage"] = "将从所选实例移除受管理的 Loader 文件。"
        ,["ConfirmModUninstallTitle"] = "卸载 Mod？"
        ,["ConfirmModUninstallMessage"] = "将从此实例移除所选的受管理 Mod。"
        ,["ConfirmSnapshotRestoreTitle"] = "恢复快照？"
        ,["ConfirmSnapshotRestoreMessage"] = "当前实例的存档数据将被所选快照替换。"
        ,["NoInstancesAction"] = "未找到实例。请在设置中选择版本根目录，或刷新后重试。"
        ,["NoLoadersAction"] = "没有兼容的 Loader。请检查所选版本后刷新。"
        ,["NoAvailableModsAction"] = "没有兼容的 Mod。请在设置中检查目录源。"
        ,["NoInstalledModsAction"] = "此实例尚未安装受管理的 Mod。"
        ,["NoSnapshotsAction"] = "尚无快照。请在上方输入名称并创建第一个快照。"
        ,["NoSpeedrunTemplatesAction"] = "没有可用模板。请在设置中检查目录源。"
        ,["NoDownloadBuildsAction"] = "没有可用版本。请在设置中检查目录源。"
        ,["OpenSettings"] = "打开设置"
        ,["SelectInstance"] = "选择实例"
        ,["InstanceSettings"] = "实例设置"
        ,["Back"] = "返回"
        ,["CloneInstance"] = "克隆实例"
        ,["CloneInstanceName"] = "新实例名称"
        ,["CopySuffix"] = "副本"
        ,["DeleteInstance"] = "删除实例"
        ,["DeleteInstanceTitle"] = "永久删除实例"
        ,["DeleteInstanceMessage"] = "游戏目录、Loader、Mod、隔离存档和存档快照将被永久删除。"
        ,["PermanentDeleteWarning"] = "此操作会永久删除实例，且无法撤销。"
        ,["DeleteBlockedGameRunning"] = "请先关闭《空洞骑士》，再删除此实例。"
        ,["DeleteBlockedDownloads"] = "请先取消或完成此实例的下载任务，再删除实例。"
        ,["DeleteBlockedTransactions"] = "请先处理未完成的文件事务，再删除此实例。"
        ,["DeleteCleanupPending"] = "实例已删除，残留文件将在下次启动时继续清理。"
        ,["DeleteRecoveryNeedsAttention"] = "存在需要处理的实例删除事务。"
        ,["CloneNameRequired"] = "请输入克隆实例名称。"
        ,["CloneVanillaOnly"] = "请选择原版实例克隆，确保 Loader 与 Mod 状态相互独立。"
        ,["LoadNormaliserSeconds"] = "加载标准化秒数"
        ,["SpeedrunTemplateMissing"] = "速通模板已不可用。"
        ,["SpeedrunBuildMissing"] = "速通对应的游戏版本已不可用。"
        ,["SpeedrunManifestMissing"] = "速通文件清单已不可用。"
        ,["SpeedrunVerified"] = "正式速通环境启动前完整性检查通过。"
        ,["SpeedrunVerificationFailed"] = "正式速通环境启动前完整性检查失败，已阻止启动。"
        ,["SpeedrunUnverifiedReport"] = "已生成未验证速通报告。"
        ,["RecoveryNeedsAttention"] = "文件事务需要手动处理，处理前禁止启动。"
        ,["AdvancedLocalLoader"] = "高级本地 Loader 导入"
        ,["LocalLoaderManifestPath"] = "Crystalfly Loader 清单（.json）"
        ,["LocalLoaderManifestRequired"] = "请选择存在的 Crystalfly Loader 清单。"
        ,["SelectLoaderManifestTitle"] = "选择 Crystalfly Loader 清单"
        ,["LoaderManifestFileType"] = "Crystalfly Loader 清单"
        ,["ImportLocalLoader"] = "导入本地 Loader"
        ,["Unverified"] = "未验证"
        ,["UnverifiedLocalLoader"] = "本地 Loader · 未验证"
        ,["VerifiedCatalogLoader"] = "目录 Loader · 安装包已验证"
        ,["FilterMods"] = "搜索 Mods"
        ,["FilterAll"] = "全部状态"
        ,["Enabled"] = "已启用"
        ,["Updates"] = "可更新"
        ,["Update"] = "更新"
        ,["UpdateAvailable"] = "有可用更新"
        ,["SelectedMods"] = "个 Mod 已选择"
        ,["Information"] = "信息"
        ,["OpenFolder"] = "打开目录"
        ,["SelectMultiple"] = "多选"
        ,["SelectAll"] = "全选"
        ,["ClearSelection"] = "取消选择"
        ,["BatchActions"] = "批量操作"
        ,["BatchEnable"] = "启用所选"
        ,["BatchDisable"] = "停用所选"
        ,["BatchUninstall"] = "卸载所选"
        ,["Enable"] = "启用"
        ,["Disable"] = "停用"
        ,["Missing"] = "缺失"
        ,["NeedsRepair"] = "需要修复"
        ,["DependencyProblem"] = "依赖异常"
        ,["NeedsAttention"] = "需要处理"
        ,["LaunchBlocked"] = "启动前检查未通过，解决问题后才能启动。"
        ,["NoUpdateAvailable"] = "所选 Mod 没有可用的目录更新。"
        ,["ReverseDependencies"] = "请先移除依赖这些 Mod 的项目，或将其一并选择"
        ,["RefreshFailed"] = "刷新失败"
        ,["GameFiles"] = "游戏文件"
        ,["LoaderStatus"] = "Loader 状态"
        ,["LogFiles"] = "日志文件"
        ,["NoLogs"] = "没有找到此实例支持的日志文件。"
        ,["RefreshLogs"] = "刷新日志"
        ,["ConfirmBulkUninstallTitle"] = "卸载所选 Mods？"
        ,["ConfirmBulkUninstallMessage"] = "将从此实例移除所选的受管理 Mods。"
        ,["CannotUninstallDependents"] = "以下已安装 Mods 依赖当前选择："
        ,["DependencyImpact"] = "依赖影响"
        ,["RepairDependencies"] = "修复依赖"
        ,["WillDelete"] = "将删除"
        ,["DependenciesWillBeMissing"] = "依赖将缺失"
        ,["WillReEnable"] = "将重新启用"
        ,["WillDownloadAndInstall"] = "将下载并安装"
        ,["CannotRepair"] = "无法修复"
        ,["Target"] = "目标"
        ,["Unresolved"] = "未解决"
        ,["GameVersions"] = "游戏版本"
        ,["ModMarket"] = "Mod 市场"
        ,["MarketTitle"] = "发现 Mod"
        ,["MarketHint"] = "浏览官方 HK ModLinks 目录，并将兼容版本安装到实例。"
        ,["MarketSearch"] = "搜索 Mod"
        ,["MarketBuild"] = "游戏版本"
        ,["MarketLoader"] = "Loader"
        ,["MarketSource"] = "来源"
        ,["MarketTag"] = "标签"
        ,["ActivityAll"] = "全部动态"
        ,["RecentlyAdded"] = "最近新增"
        ,["RecentlyUpdated"] = "最近更新"
        ,["MarketEmpty"] = "没有符合当前筛选条件的 Mod。"
        ,["ViewDetails"] = "查看详情"
        ,["BackToMarket"] = "返回 Mod 市场"
        ,["Authors"] = "作者"
        ,["Tags"] = "标签"
        ,["Integrations"] = "集成"
        ,["SupportedBuilds"] = "支持版本"
        ,["Dependencies"] = "依赖"
        ,["QueueDetails"] = "任务明细"
        ,["Source"] = "来源"
        ,["Repository"] = "仓库"
        ,["Readme"] = "README"
        ,["LatestReleaseNotes"] = "最新发行说明"
        ,["ReinstallMod"] = "重装 Mod"
        ,["GlobalSettings"] = "全局设置"
        ,["DeleteGlobalSettings"] = "删除全局设置"
        ,["OpenLogs"] = "查看日志"
        ,["ContentRemote"] = "在线内容"
        ,["ContentCached"] = "缓存内容"
        ,["ContentUnavailable"] = "内容不可用"
        ,["OfficialEnglishDescription"] = "官方英文说明"
        ,["Issues"] = "问题反馈"
        ,["InstallModTitle"] = "安装 Mod"
        ,["InstallToInstance"] = "选择目标实例"
        ,["NoInstallTargets"] = "没有可用于安装此 Mod 的实例。"
        ,["InstallSelectedMod"] = "安装所选 Mod"
        ,["MarketWillInstallLoader"] = "将先安装 {0}"
        ,["MarketWrongLoaderBlocked"] = "已安装其他 Loader"
        ,["MarketDriftedBlocked"] = "Loader 文件已漂移，请先修复"
        ,["MarketIncompatibleBlocked"] = "此游戏版本与 Mod 或其依赖不兼容"
        ,["OfficialSpeedrunModBlocked"] = "正式速通实例禁止安装 Mod"
        ,["ExternalLoader"] = "外部安装"
        ,["HKModLinks"] = "HK ModLinks"
        ,["HKModLinksHint"] = "官方 Mod 目录 · 只读"
        ,["CatalogRemote"] = "远程目录"
        ,["CatalogCached"] = "已缓存"
        ,["CatalogFailed"] = "加载失败"
        ,["DownloadQueue"] = "下载队列"
        ,["DownloadQueueHint"] = "下载会在后台继续；仅在游戏退出后修改目标实例文件。"
        ,["DownloadQueueEmpty"] = "暂无下载任务。请下载游戏版本，或从 Mod 市场安装 Mod。"
        ,["AddToDownloadQueue"] = "加入下载队列"
        ,["AddedToDownloadQueue"] = "已加入下载队列"
        ,["QueueTaskAlreadyExists"] = "下载队列中已存在此任务"
        ,["RequiredComponents"] = "所需组件"
        ,["MainMod"] = "主 Mod"
        ,["Dependency"] = "前置依赖"
        ,["WillInstall"] = "将安装"
        ,["WillUpdate"] = "将更新"
        ,["InstallationPlan"] = "安装计划"
        ,["ConfirmCloseDownloadsTitle"] = "仍有未完成下载，是否关闭？"
        ,["ConfirmCloseDownloadsMessage"] = "正在传输的任务会在安全边界停止；未完成和失败任务将保存，并可在下次启动后继续。"
        ,["QueueTarget"] = "目标实例"
        ,["QueueRetry"] = "重试"
        ,["QueueRetryCount"] = "已重试：{0}"
        ,["QueueStatePending"] = "等待中"
        ,["QueueStateRunning"] = "执行中"
        ,["QueueStateTransferring"] = "正在下载"
        ,["QueueStateWaitingForGameExit"] = "等待游戏退出"
        ,["QueueStateWaitingForSteamLogin"] = "等待登录 Steam"
        ,["QueueStateInstalling"] = "正在安装"
        ,["QueueStateCompleted"] = "已完成"
        ,["QueueStateFailed"] = "失败"
        ,["QueueStateBlocked"] = "已阻塞"
        ,["QueueStateCanceled"] = "已取消"
        ,["QueueStageStarting"] = "正在开始"
        ,["QueueStageRetrying"] = "正在重试"
        ,["QueueStageCached"] = "使用已缓存安装包"
        ,["QueueStageSatisfied"] = "已安装"
        ,["CloseWithDownloadsTitle"] = "仍有下载任务，确定关闭？"
        ,["CloseWithDownloadsMessage"] = "活动下载会在安全边界取消，并在下次启动时恢复到队列。"
        ,["ActiveDownloads"] = "{0} 个活动下载"
    };

    private IReadOnlyDictionary<string, string> values = Chinese;

    public string this[string key] => values.TryGetValue(key, out var value) ? value : key;

    public CultureInfo Culture { get; private set; } = CultureInfo.GetCultureInfo("zh-CN");

    public void Apply(UiLanguage language)
    {
        var useChinese = language == UiLanguage.SimplifiedChinese
            || (language == UiLanguage.FollowSystem
                && CultureInfo.CurrentUICulture.Name.StartsWith("zh", StringComparison.OrdinalIgnoreCase));
        Culture = CultureInfo.GetCultureInfo(useChinese ? "zh-CN" : "en-US");
        values = useChinese ? Chinese : English;
        OnPropertyChanged("Item[]");
    }
}
