using System.Globalization;
using Crystalfly.Core.Configuration;

namespace Crystalfly.App.ViewModels;

public sealed class LocalizationViewModel : ViewModelBase
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["NavLaunch"] = "Launch",
        ["NavVersions"] = "Instances",
        ["NavManage"] = "Manage",
        ["NavSpeedrun"] = "Speedrun",
        ["NavDownloads"] = "Downloads",
        ["NavSettings"] = "Settings",
        ["Ready"] = "Ready",
        ["ReadyHint"] = "The selected instance passed launch checks.",
        ["NoInstance"] = "No instance selected",
        ["ChooseRoot"] = "Choose a version root to discover Hollow Knight instances.",
        ["LaunchGame"] = "Launch game",
        ["Refresh"] = "Refresh",
        ["ManageInstance"] = "Manage instance",
        ["LoaderFiles"] = "Game and loader files",
        ["ModDependencies"] = "Mod dependencies",
        ["SaveIsolation"] = "Save isolation",
        ["Complete"] = "Complete",
        ["NoConflicts"] = "No conflicts",
        ["Mounted"] = "Ready",
        ["Instances"] = "Instances",
        ["InstancesHint"] = "Known versions and full-copy environments under the selected root.",
        ["SearchInstances"] = "Search instances",
        ["Overview"] = "Overview",
        ["Loader"] = "Loader",
        ["Mods"] = "Mods",
        ["Snapshots"] = "Save Snapshots",
        ["Logs"] = "Logs",
        ["SpeedrunTitle"] = "Official speedrun environments",
        ["SpeedrunHint"] = "Create a dedicated verified copy. Daily instances are never modified.",
        ["CreateEnvironment"] = "Create environment",
        ["DownloadsTitle"] = "Downloads",
        ["DownloadsHint"] = "Steam public builds and cached packages.",
        ["SteamAccount"] = "Steam account",
        ["SignInQr"] = "Sign in with QR",
        ["SignOut"] = "Sign out",
        ["SettingsTitle"] = "Settings",
        ["VersionRoot"] = "Version root",
        ["Browse"] = "Browse",
        ["Language"] = "Language",
        ["Theme"] = "Theme",
        ["System"] = "System",
        ["Light"] = "Light",
        ["Dark"] = "Dark",
        ["FollowSystem"] = "Follow system",
        ["SimplifiedChinese"] = "Simplified Chinese",
        ["English"] = "English",
        ["Vanilla"] = "Vanilla",
        ["UnknownBuild"] = "Unknown build · vanilla only",
        ["Local"] = "Local",
        ["Installed"] = "Installed",
        ["Disabled"] = "Disabled",
        ["NoMods"] = "No managed mods",
        ["NoSnapshots"] = "No snapshots",
        ["CreateSnapshot"] = "Create snapshot",
        ["Restore"] = "Restore",
        ["StatusChecking"] = "Checking instances...",
        ["StatusReady"] = "Ready",
        ["OperationFailed"] = "Operation failed"
        ,["OperationComplete"] = "Operation completed"
        ,["SelectLoader"] = "Select a loader first."
        ,["SelectMod"] = "Select a mod first."
        ,["SelectSnapshot"] = "Select a snapshot first."
        ,["SelectSpeedrunTemplate"] = "Select a speedrun template first."
        ,["SnapshotNameRequired"] = "Enter a snapshot name."
        ,["LoaderConflict"] = "Conflicting loader files require manual repair."
        ,["RepairBeforeSwitch"] = "Repair the current loader before switching."
        ,["LoaderSwitchBlockedByMods"] = "Uninstall every managed mod, including disabled and local mods, before switching loaders. The current loader and mod files were left unchanged."
        ,["ExternalLoaderBlocked"] = "An unmanaged loader is present. To protect the original game files, Crystalfly will not overwrite or repair it. Download or create a clean instance before installing a loader."
        ,["LoaderRequired"] = "Install the required loader first."
        ,["WrongLoader"] = "This mod requires another loader"
        ,["UpdateRequired"] = "Update is required before reinstalling"
        ,["CloseGameFirst"] = "Close every Hollow Knight process before changing this instance."
        ,["NoVanillaSource"] = "No clean vanilla instance matches this template."
        ,["SpeedrunNeedsVerification"] = "Dedicated copy created. Run verification before an official attempt."
        ,["SpeedrunUnverified"] = "Dedicated copy created as unverified because the catalog has no trusted file manifest."
        ,["InstallOrSwitch"] = "Install or switch"
        ,["Repair"] = "Repair"
        ,["Uninstall"] = "Uninstall"
        ,["EnableDisable"] = "Enable / disable"
        ,["Install"] = "Install"
        ,["AvailableMods"] = "Available mods"
        ,["InstalledMods"] = "Installed Mods"
        ,["SnapshotName"] = "Snapshot name"
        ,["Template"] = "Template"
        ,["EnvironmentName"] = "Environment name"
        ,["LocalModPath"] = "Local ZIP or DLL path"
        ,["ImportLocalMod"] = "Import local mod"
        ,["LocalModPathRequired"] = "Choose an existing local ZIP or DLL."
        ,["LocalModType"] = "Only ZIP and DLL mod imports are supported."
        ,["Cancel"] = "Cancel"
        ,["Save"] = "Save"
        ,["CustomCatalogSources"] = "Custom catalog sources"
        ,["SelectVersionRootTitle"] = "Select Hollow Knight version root"
        ,["SelectModPackageTitle"] = "Select a mod package"
        ,["ModFileType"] = "Hollow Knight mod"
        ,["Confirm"] = "Continue"
        ,["ConfirmLoaderUninstallTitle"] = "Uninstall loader?"
        ,["ConfirmLoaderUninstallMessage"] = "Managed loader files will be removed from the selected instance."
        ,["ConfirmModUninstallTitle"] = "Uninstall mod?"
        ,["ConfirmModUninstallMessage"] = "The selected managed mod will be removed from this instance."
        ,["ConfirmSnapshotRestoreTitle"] = "Restore snapshot?"
        ,["ConfirmSnapshotRestoreMessage"] = "Current instance save data will be replaced with the selected snapshot."
        ,["NoInstancesAction"] = "No instances found. Choose a version root in Settings or refresh."
        ,["NoLoadersAction"] = "No compatible loaders. Refresh after checking the selected build."
        ,["NoAvailableModsAction"] = "No compatible mods. Check catalog sources in Settings."
        ,["NoInstalledModsAction"] = "No managed mods are installed in this instance."
        ,["NoSnapshotsAction"] = "No snapshots. Enter a name above to create the first one."
        ,["NoSpeedrunTemplatesAction"] = "No templates available. Check catalog sources in Settings."
        ,["NoDownloadBuildsAction"] = "No builds available. Check catalog sources in Settings."
        ,["OpenSettings"] = "Open settings"
        ,["Back"] = "Back"
        ,["CloneInstance"] = "Clone instance"
        ,["CloneInstanceName"] = "New instance name"
        ,["CloneNameRequired"] = "Enter a name for the cloned instance."
        ,["CloneVanillaOnly"] = "Clone a vanilla instance so loader and mod state stay independent."
        ,["LoadNormaliserSeconds"] = "Load normaliser seconds"
        ,["SpeedrunTemplateMissing"] = "The speedrun template is no longer available."
        ,["SpeedrunBuildMissing"] = "The speedrun game build is no longer available."
        ,["SpeedrunManifestMissing"] = "The speedrun file manifest is no longer available."
        ,["SpeedrunVerified"] = "Official speedrun pre-launch integrity check passed."
        ,["SpeedrunVerificationFailed"] = "Official speedrun pre-launch integrity check failed; launch is blocked."
        ,["SpeedrunUnverifiedReport"] = "Unverified speedrun report generated."
        ,["RecoveryNeedsAttention"] = "A file transaction needs manual attention before launch."
        ,["AdvancedLocalLoader"] = "Advanced local loader import"
        ,["LocalLoaderManifestPath"] = "Crystalfly loader manifest (.json)"
        ,["LocalLoaderManifestRequired"] = "Choose an existing Crystalfly loader manifest."
        ,["SelectLoaderManifestTitle"] = "Select Crystalfly loader manifest"
        ,["LoaderManifestFileType"] = "Crystalfly loader manifest"
        ,["ImportLocalLoader"] = "Import local loader"
        ,["Unverified"] = "Unverified"
        ,["UnverifiedLocalLoader"] = "Local loader · unverified"
        ,["VerifiedCatalogLoader"] = "Catalog loader · verified package"
        ,["FilterMods"] = "Search mods"
        ,["FilterAll"] = "All statuses"
        ,["Enabled"] = "Enabled"
        ,["Updates"] = "Updates"
        ,["Update"] = "Update"
        ,["UpdateAvailable"] = "Update available"
        ,["SelectedMods"] = "mods selected"
        ,["Enable"] = "Enable"
        ,["Disable"] = "Disable"
        ,["Missing"] = "Missing"
        ,["NeedsRepair"] = "Needs repair"
        ,["DependencyProblem"] = "Dependency problem"
        ,["NeedsAttention"] = "Needs attention"
        ,["LaunchBlocked"] = "Launch is blocked until the failed preflight checks are resolved."
        ,["NoUpdateAvailable"] = "No catalog update is available for the selected mod."
        ,["ReverseDependencies"] = "Dependent mods must be removed or included first"
        ,["RefreshFailed"] = "Refresh failed"
        ,["GameFiles"] = "Game files"
        ,["LoaderStatus"] = "Loader state"
        ,["LogFiles"] = "Log files"
        ,["NoLogs"] = "No supported log files were found for this instance."
        ,["RefreshLogs"] = "Refresh logs"
        ,["ConfirmBulkUninstallTitle"] = "Uninstall selected mods?"
        ,["ConfirmBulkUninstallMessage"] = "The selected managed mods will be removed from this instance."
        ,["CannotUninstallDependents"] = "These installed mods depend on the selection:"
        ,["GameVersions"] = "Game versions"
        ,["ModMarket"] = "Mod Market"
        ,["MarketTitle"] = "Discover mods"
        ,["MarketHint"] = "Browse the official HK ModLinks catalog and install a compatible release into an instance."
        ,["MarketSearch"] = "Search mods"
        ,["MarketBuild"] = "Game build"
        ,["MarketLoader"] = "Loader"
        ,["MarketSource"] = "Source"
        ,["MarketTag"] = "Tag"
        ,["MarketEmpty"] = "No mods match the current filters."
        ,["ViewDetails"] = "View details"
        ,["BackToMarket"] = "Back to Mod Market"
        ,["Authors"] = "Authors"
        ,["Tags"] = "Tags"
        ,["Integrations"] = "Integrations"
        ,["SupportedBuilds"] = "Supported builds"
        ,["Dependencies"] = "Dependencies"
        ,["Source"] = "Source"
        ,["Repository"] = "Repository"
        ,["Issues"] = "Issues"
        ,["InstallModTitle"] = "Install mod"
        ,["InstallToInstance"] = "Choose target instance"
        ,["NoInstallTargets"] = "No instances are available for this mod."
        ,["InstallSelectedMod"] = "Install selected mod"
        ,["MarketWillInstallLoader"] = "Will install {0} first"
        ,["MarketWrongLoaderBlocked"] = "Another Loader is installed"
        ,["MarketDriftedBlocked"] = "Loader files have drifted and must be repaired first"
        ,["MarketIncompatibleBlocked"] = "This game build is not compatible with the Mod and its dependencies"
        ,["OfficialSpeedrunModBlocked"] = "Official speedrun instances cannot install Mods"
        ,["ExternalLoader"] = "External"
        ,["HKModLinks"] = "HK ModLinks"
        ,["HKModLinksHint"] = "Official mod catalog · read-only"
        ,["CatalogRemote"] = "Remote"
        ,["CatalogCached"] = "Cached"
        ,["CatalogFailed"] = "Failed"
    };

    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["NavLaunch"] = "启动",
        ["NavVersions"] = "实例",
        ["NavManage"] = "管理",
        ["NavSpeedrun"] = "速通",
        ["NavDownloads"] = "下载",
        ["NavSettings"] = "设置",
        ["Ready"] = "准备就绪",
        ["ReadyHint"] = "当前实例已通过启动前检查。",
        ["NoInstance"] = "未选择实例",
        ["ChooseRoot"] = "请选择版本根目录以发现空洞骑士实例。",
        ["LaunchGame"] = "启动游戏",
        ["Refresh"] = "刷新",
        ["ManageInstance"] = "管理实例",
        ["LoaderFiles"] = "游戏与 Loader 文件",
        ["ModDependencies"] = "Mod 依赖关系",
        ["SaveIsolation"] = "存档隔离",
        ["Complete"] = "完整",
        ["NoConflicts"] = "无冲突",
        ["Mounted"] = "已就绪",
        ["Instances"] = "实例",
        ["InstancesHint"] = "所选根目录中的已知版本与完整复制环境。",
        ["SearchInstances"] = "搜索实例",
        ["Overview"] = "概览",
        ["Loader"] = "Loader",
        ["Mods"] = "Mods",
        ["Snapshots"] = "存档快照",
        ["Logs"] = "日志",
        ["SpeedrunTitle"] = "正式速通环境",
        ["SpeedrunHint"] = "创建专用验证副本，不修改日常实例。",
        ["CreateEnvironment"] = "创建环境",
        ["DownloadsTitle"] = "下载",
        ["DownloadsHint"] = "Steam public 版本与已缓存安装包。",
        ["SteamAccount"] = "Steam 账号",
        ["SignInQr"] = "扫码登录",
        ["SignOut"] = "退出账号",
        ["SettingsTitle"] = "设置",
        ["VersionRoot"] = "版本根目录",
        ["Browse"] = "浏览",
        ["Language"] = "语言",
        ["Theme"] = "主题",
        ["System"] = "系统",
        ["Light"] = "亮色",
        ["Dark"] = "暗色",
        ["FollowSystem"] = "跟随系统",
        ["SimplifiedChinese"] = "简体中文",
        ["English"] = "English",
        ["Vanilla"] = "原版",
        ["UnknownBuild"] = "未知版本 · 仅允许原版",
        ["Local"] = "本地",
        ["Installed"] = "已安装",
        ["Disabled"] = "已停用",
        ["NoMods"] = "没有受管理的 Mod",
        ["NoSnapshots"] = "没有快照",
        ["CreateSnapshot"] = "创建快照",
        ["Restore"] = "恢复",
        ["StatusChecking"] = "正在检查实例...",
        ["StatusReady"] = "就绪",
        ["OperationFailed"] = "操作失败"
        ,["OperationComplete"] = "操作完成"
        ,["SelectLoader"] = "请先选择 Loader。"
        ,["SelectMod"] = "请先选择 Mod。"
        ,["SelectSnapshot"] = "请先选择快照。"
        ,["SelectSpeedrunTemplate"] = "请先选择速通模板。"
        ,["SnapshotNameRequired"] = "请输入快照名称。"
        ,["LoaderConflict"] = "存在冲突的 Loader 文件，需要手动修复。"
        ,["RepairBeforeSwitch"] = "切换前请先修复当前 Loader。"
        ,["LoaderSwitchBlockedByMods"] = "切换 Loader 前请先卸载全部受管 Mod（包括已停用和本地 Mod）；当前 Loader 与 Mod 文件均未更改。"
        ,["ExternalLoaderBlocked"] = "检测到未由 Crystalfly 管理的 Loader。为了保护原始游戏文件，无法直接覆盖或修复；请先下载或创建干净实例，再安装 Loader。"
        ,["LoaderRequired"] = "请先安装所需 Loader。"
        ,["WrongLoader"] = "此 Mod 需要其他 Loader"
        ,["UpdateRequired"] = "重新安装前需要先更新"
        ,["CloseGameFirst"] = "修改实例前请关闭所有空洞骑士进程。"
        ,["NoVanillaSource"] = "没有与此模板匹配的纯净原版实例。"
        ,["SpeedrunNeedsVerification"] = "专用副本已创建，正式开跑前请执行验证。"
        ,["SpeedrunUnverified"] = "专用副本已创建，但目录缺少可信文件清单，因此标记为未验证。"
        ,["InstallOrSwitch"] = "安装或切换"
        ,["Repair"] = "修复"
        ,["Uninstall"] = "卸载"
        ,["EnableDisable"] = "启用 / 停用"
        ,["Install"] = "安装"
        ,["AvailableMods"] = "可用 Mods"
        ,["InstalledMods"] = "已安装 Mod"
        ,["SnapshotName"] = "快照名称"
        ,["Template"] = "模板"
        ,["EnvironmentName"] = "环境名称"
        ,["LocalModPath"] = "本地 ZIP 或 DLL 路径"
        ,["ImportLocalMod"] = "导入本地 Mod"
        ,["LocalModPathRequired"] = "请选择存在的本地 ZIP 或 DLL。"
        ,["LocalModType"] = "仅支持导入 ZIP 与 DLL。"
        ,["Cancel"] = "取消"
        ,["Save"] = "保存"
        ,["CustomCatalogSources"] = "自定义目录源"
        ,["SelectVersionRootTitle"] = "选择空洞骑士版本根目录"
        ,["SelectModPackageTitle"] = "选择 Mod 安装包"
        ,["ModFileType"] = "空洞骑士 Mod"
        ,["Confirm"] = "继续"
        ,["ConfirmLoaderUninstallTitle"] = "卸载 Loader？"
        ,["ConfirmLoaderUninstallMessage"] = "将从所选实例移除受管理的 Loader 文件。"
        ,["ConfirmModUninstallTitle"] = "卸载 Mod？"
        ,["ConfirmModUninstallMessage"] = "将从此实例移除所选的受管理 Mod。"
        ,["ConfirmSnapshotRestoreTitle"] = "恢复快照？"
        ,["ConfirmSnapshotRestoreMessage"] = "当前实例的存档数据将被所选快照替换。"
        ,["NoInstancesAction"] = "未找到实例。请在设置中选择版本根目录，或刷新后重试。"
        ,["NoLoadersAction"] = "没有兼容的 Loader。请检查所选版本后刷新。"
        ,["NoAvailableModsAction"] = "没有兼容的 Mod。请在设置中检查目录源。"
        ,["NoInstalledModsAction"] = "此实例尚未安装受管理的 Mod。"
        ,["NoSnapshotsAction"] = "尚无快照。请在上方输入名称并创建第一个快照。"
        ,["NoSpeedrunTemplatesAction"] = "没有可用模板。请在设置中检查目录源。"
        ,["NoDownloadBuildsAction"] = "没有可用版本。请在设置中检查目录源。"
        ,["OpenSettings"] = "打开设置"
        ,["Back"] = "返回"
        ,["CloneInstance"] = "克隆实例"
        ,["CloneInstanceName"] = "新实例名称"
        ,["CloneNameRequired"] = "请输入克隆实例名称。"
        ,["CloneVanillaOnly"] = "请选择原版实例克隆，确保 Loader 与 Mod 状态相互独立。"
        ,["LoadNormaliserSeconds"] = "加载标准化秒数"
        ,["SpeedrunTemplateMissing"] = "速通模板已不可用。"
        ,["SpeedrunBuildMissing"] = "速通对应的游戏版本已不可用。"
        ,["SpeedrunManifestMissing"] = "速通文件清单已不可用。"
        ,["SpeedrunVerified"] = "正式速通环境启动前完整性检查通过。"
        ,["SpeedrunVerificationFailed"] = "正式速通环境启动前完整性检查失败，已阻止启动。"
        ,["SpeedrunUnverifiedReport"] = "已生成未验证速通报告。"
        ,["RecoveryNeedsAttention"] = "文件事务需要手动处理，处理前禁止启动。"
        ,["AdvancedLocalLoader"] = "高级本地 Loader 导入"
        ,["LocalLoaderManifestPath"] = "Crystalfly Loader 清单（.json）"
        ,["LocalLoaderManifestRequired"] = "请选择存在的 Crystalfly Loader 清单。"
        ,["SelectLoaderManifestTitle"] = "选择 Crystalfly Loader 清单"
        ,["LoaderManifestFileType"] = "Crystalfly Loader 清单"
        ,["ImportLocalLoader"] = "导入本地 Loader"
        ,["Unverified"] = "未验证"
        ,["UnverifiedLocalLoader"] = "本地 Loader · 未验证"
        ,["VerifiedCatalogLoader"] = "目录 Loader · 安装包已验证"
        ,["FilterMods"] = "搜索 Mods"
        ,["FilterAll"] = "全部状态"
        ,["Enabled"] = "已启用"
        ,["Updates"] = "可更新"
        ,["Update"] = "更新"
        ,["UpdateAvailable"] = "有可用更新"
        ,["SelectedMods"] = "个 Mod 已选择"
        ,["Enable"] = "启用"
        ,["Disable"] = "停用"
        ,["Missing"] = "缺失"
        ,["NeedsRepair"] = "需要修复"
        ,["DependencyProblem"] = "依赖异常"
        ,["NeedsAttention"] = "需要处理"
        ,["LaunchBlocked"] = "启动前检查未通过，解决问题后才能启动。"
        ,["NoUpdateAvailable"] = "所选 Mod 没有可用的目录更新。"
        ,["ReverseDependencies"] = "请先移除依赖这些 Mod 的项目，或将其一并选择"
        ,["RefreshFailed"] = "刷新失败"
        ,["GameFiles"] = "游戏文件"
        ,["LoaderStatus"] = "Loader 状态"
        ,["LogFiles"] = "日志文件"
        ,["NoLogs"] = "没有找到此实例支持的日志文件。"
        ,["RefreshLogs"] = "刷新日志"
        ,["ConfirmBulkUninstallTitle"] = "卸载所选 Mods？"
        ,["ConfirmBulkUninstallMessage"] = "将从此实例移除所选的受管理 Mods。"
        ,["CannotUninstallDependents"] = "以下已安装 Mods 依赖当前选择："
        ,["GameVersions"] = "游戏版本"
        ,["ModMarket"] = "Mod 市场"
        ,["MarketTitle"] = "发现 Mod"
        ,["MarketHint"] = "浏览官方 HK ModLinks 目录，并将兼容版本安装到实例。"
        ,["MarketSearch"] = "搜索 Mod"
        ,["MarketBuild"] = "游戏版本"
        ,["MarketLoader"] = "Loader"
        ,["MarketSource"] = "来源"
        ,["MarketTag"] = "标签"
        ,["MarketEmpty"] = "没有符合当前筛选条件的 Mod。"
        ,["ViewDetails"] = "查看详情"
        ,["BackToMarket"] = "返回 Mod 市场"
        ,["Authors"] = "作者"
        ,["Tags"] = "标签"
        ,["Integrations"] = "集成"
        ,["SupportedBuilds"] = "支持版本"
        ,["Dependencies"] = "依赖"
        ,["Source"] = "来源"
        ,["Repository"] = "仓库"
        ,["Issues"] = "问题反馈"
        ,["InstallModTitle"] = "安装 Mod"
        ,["InstallToInstance"] = "选择目标实例"
        ,["NoInstallTargets"] = "没有可用于安装此 Mod 的实例。"
        ,["InstallSelectedMod"] = "安装所选 Mod"
        ,["MarketWillInstallLoader"] = "将先安装 {0}"
        ,["MarketWrongLoaderBlocked"] = "已安装其他 Loader"
        ,["MarketDriftedBlocked"] = "Loader 文件已漂移，请先修复"
        ,["MarketIncompatibleBlocked"] = "此游戏版本与 Mod 或其依赖不兼容"
        ,["OfficialSpeedrunModBlocked"] = "正式速通实例禁止安装 Mod"
        ,["ExternalLoader"] = "外部安装"
        ,["HKModLinks"] = "HK ModLinks"
        ,["HKModLinksHint"] = "官方 Mod 目录 · 只读"
        ,["CatalogRemote"] = "远程目录"
        ,["CatalogCached"] = "已缓存"
        ,["CatalogFailed"] = "加载失败"
    };

    private IReadOnlyDictionary<string, string> values = Chinese;

    public string this[string key] => values.TryGetValue(key, out var value) ? value : key;

    public CultureInfo Culture { get; private set; } = CultureInfo.GetCultureInfo("zh-CN");

    public void Apply(UiLanguage language)
    {
        var useChinese = language == UiLanguage.SimplifiedChinese
            || (language == UiLanguage.FollowSystem
                && CultureInfo.CurrentUICulture.Name.StartsWith("zh", StringComparison.OrdinalIgnoreCase));
        Culture = CultureInfo.GetCultureInfo(useChinese ? "zh-CN" : "en-US");
        values = useChinese ? Chinese : English;
        OnPropertyChanged("Item[]");
    }
}
